-- LaunchPad — additional demo examples (more submitted / needs_info / rejected).
-- Idempotent: ON CONFLICT DO NOTHING + guarded comment inserts.
-- Run in the Supabase SQL editor after 0001 + 0002.

insert into submissions (id, submitted_at, form_data, status, owner_email, business_unit)
values ('seed-ocfo-invoice', now() - interval '5 hours', '{"submitterName": "Karen Diallo", "submitterEmail": "karen.diallo@uspto.gov", "submitterRole": "manager", "submitterOffice": "ocfo", "useCaseTitle": "Invoice Anomaly Detection for Financial Operations", "publicIndicator": "public", "useCaseDescription": "An ML model that flags anomalous vendor invoices (duplicate, out-of-pattern amounts, mismatched POs) for analyst review before payment.", "coreProblem": "OCFO analysts manually spot-check a fraction of invoices; anomalies slip through and are caught late in reconciliation.", "problemImpact": "~40,000 invoices/year, only ~10% reviewed in depth. Late catches drive rework and occasional improper payments.", "impactedUsersCount": "10_50", "targetAudience": "other", "proposedSolution": "Anomaly model over historical invoice/PO data; scores each invoice and routes high-risk ones to an analyst. Analyst decides — model never blocks payment.", "businessValue": "Shifts analysts from sampling to exception-handling; reduces improper payments and reconciliation rework.", "costSavings": "250k_1m", "usptoFocusArea": ["goal_employee_experience", "ai_infrastructure"], "successMetrics": "Improper-payment rate; % anomalies caught pre-payment; analyst hours on routine review.", "timelineForResults": "3_6", "implementationComplexity": "medium", "involvesSensitiveData": "no", "aiModelSourcing": "open_source_us", "aiDecisionalImpact": "no", "aiHumanReview": "yes", "readinessScore": "needs_work", "readinessSummary": "Promising operational case; needs a measured baseline for improper-payment rate and confirmation of data access.", "executiveSummary": "OCFO reviews only a fraction of ~40,000 annual invoices by hand, so anomalies surface late in reconciliation. An anomaly model would score invoices and route high-risk ones to analysts, who keep the decision. Needs a measured baseline before scoring.", "reviewStatus": "submitted"}'::jsonb, 'submitted', 'karen.diallo@uspto.gov', 'ocfo')
on conflict (id) do nothing;

insert into submissions (id, submitted_at, form_data, status, owner_email, business_unit)
values ('seed-patents-onboarding', now() - interval '11 hours', '{"submitterName": "Daniel Roth", "submitterEmail": "daniel.roth@uspto.gov", "submitterRole": "supervisory_examiner", "submitterOffice": "patents", "useCaseTitle": "Examiner Onboarding Knowledge Assistant", "publicIndicator": "public", "useCaseDescription": "A cited-source assistant that answers new examiners'' procedure questions (MPEP, art-unit practice, PE2E how-tos) during their first year.", "coreProblem": "New examiners ramp slowly and lean heavily on SPEs for repetitive procedural questions.", "problemImpact": "Each cohort of new examiners generates heavy SPE mentoring load on repeatable MPEP/procedure questions.", "impactedUsersCount": "50_500", "targetAudience": "patent_examiner", "proposedSolution": "RAG assistant over the MPEP and internal procedure docs with citations; escalates to SPE when unsure.", "businessValue": "Faster examiner ramp; frees SPE time for substantive mentoring and quality review.", "costSavings": "50k_250k", "usptoFocusArea": ["goal_employee_experience", "ai_workforce"], "successMetrics": "Time-to-productivity for new examiners; SPE hours on routine Q&A; assistant answer-acceptance rate.", "timelineForResults": "6_12", "implementationComplexity": "low", "involvesSensitiveData": "no", "aiModelSourcing": "open_source_us", "aiDecisionalImpact": "no", "aiHumanReview": "yes", "readinessScore": "needs_work", "readinessSummary": "Low-risk internal assistant. Needs a baseline for ramp time and a content owner for the MPEP corpus.", "executiveSummary": "New patent examiners ramp slowly and lean on SPEs for repeatable procedure questions. A cited RAG assistant over the MPEP and internal docs would deflect routine questions and escalate the rest. Low risk; needs a ramp-time baseline and a content owner.", "reviewStatus": "submitted"}'::jsonb, 'submitted', 'daniel.roth@uspto.gov', 'patents')
on conflict (id) do nothing;

insert into submissions (id, submitted_at, form_data, status, owner_email, business_unit)
values ('seed-opia-inquiry', now() - interval '18 hours', '{"submitterName": "Lena Park", "submitterEmail": "lena.park@uspto.gov", "submitterRole": "other", "submitterOffice": "opia", "useCaseTitle": "Public Inquiry Auto-Responder (Draft Suggestions)", "publicIndicator": "public", "useCaseDescription": "Suggests draft replies to common public/press inquiries for a comms specialist to edit and approve. Never auto-sends.", "coreProblem": "OPIA fields repetitive public inquiries; drafting from scratch each time is slow.", "problemImpact": "High volume of repeat questions; response SLAs slip during peak periods.", "impactedUsersCount": "lt_10", "targetAudience": "other", "proposedSolution": "RAG over approved public messaging + FAQ; drafts a suggested reply with citations; specialist edits and sends.", "businessValue": "Faster, more consistent public responses; specialists focus on novel/sensitive inquiries.", "costSavings": "lt_50k", "usptoFocusArea": ["goal_employee_experience"], "successMetrics": "Median response time; % responses using a suggested draft; consistency review pass rate.", "timelineForResults": "3_6", "implementationComplexity": "low", "involvesSensitiveData": "no", "aiModelSourcing": "american", "aiDecisionalImpact": "no", "aiHumanReview": "yes", "readinessScore": "needs_work", "readinessSummary": "Reasonable comms-efficiency case. Confirm the approved-messaging corpus and a human-approval gate on every send.", "executiveSummary": "OPIA handles many repetitive public inquiries and drafts each reply from scratch. A draft-suggestion assistant over approved messaging would speed consistent responses, with a specialist editing and sending every reply. Confirm the source corpus and the human-approval gate.", "reviewStatus": "submitted"}'::jsonb, 'submitted', 'lena.park@uspto.gov', 'opia')
on conflict (id) do nothing;

insert into submissions (id, submitted_at, form_data, status, owner_email, business_unit)
values ('seed-trademarks-specimen', now() - interval '26 hours', '{"submitterName": "Omar Haddad", "submitterEmail": "omar.haddad@uspto.gov", "submitterRole": "trademark_examiner", "submitterOffice": "trademarks", "useCaseTitle": "Specimen Acceptability Pre-Check", "publicIndicator": "public", "useCaseDescription": "Flags likely-unacceptable trademark specimens (mockups, digitally altered images) for examiner attention.", "coreProblem": "Examiners manually assess specimen acceptability; questionable specimens are easy to miss at volume.", "problemImpact": "Specimen review is a known time sink and a source of inconsistent outcomes across examiners.", "impactedUsersCount": "50_500", "targetAudience": "trademark_examiner", "proposedSolution": "Image model trained on accepted/refused specimens; flags likely-unacceptable ones with a reason. Examiner decides.", "businessValue": "More consistent specimen review; less time on clearly-acceptable cases.", "costSavings": "50k_250k", "usptoFocusArea": ["goal_pendency_quality"], "successMetrics": "Examiner agreement with flags; time per specimen; consistency across examiners.", "timelineForResults": "6_12", "implementationComplexity": "medium", "involvesSensitiveData": "no", "aiModelSourcing": "unknown", "aiDecisionalImpact": "no", "aiHumanReview": "yes", "readinessScore": "needs_work", "readinessSummary": "Good fit, but model sourcing is unconfirmed and there''s no labeled training set identified yet.", "executiveSummary": "Trademark specimen acceptability is reviewed by hand and questionable specimens slip through at volume. An image model would flag likely-unacceptable specimens with a reason for examiner decision. Needs a labeled training set and confirmed American-built sourcing.", "comments": [{"id": "c-tm-spec-1", "authorName": "Jonathan Moody", "authorRole": "reviewer", "body": "Like this. Two things before scoring: where does the labeled specimen training set come from, and can you confirm the model sourcing? Right now it''s marked unknown, which is a blocker under the EO.", "createdAt": "2026-05-31T15:00:00Z"}], "reviewStatus": "needs_info"}'::jsonb, 'needs_info', 'omar.haddad@uspto.gov', 'trademarks')
on conflict (id) do nothing;
insert into submission_comments (submission_id, author_name, author_role, body, created_at)
select 'seed-trademarks-specimen', 'Jonathan Moody', 'reviewer', 'Like this. Two things before scoring: where does the labeled specimen training set come from, and can you confirm the model sourcing? Right now it''s marked unknown, which is a blocker under the EO.', now()
where not exists (select 1 from submission_comments where submission_id = 'seed-trademarks-specimen');

insert into submissions (id, submitted_at, form_data, status, owner_email, business_unit)
values ('seed-ocio-outage', now() - interval '33 hours', '{"submitterName": "Tariq Nguyen", "submitterEmail": "tariq.nguyen@uspto.gov", "submitterRole": "it_staff", "submitterOffice": "ocio", "useCaseTitle": "Network Outage Predictive Alerts", "publicIndicator": "public", "useCaseDescription": "Predicts likely network/service degradations from telemetry so ops can act before users are impacted.", "coreProblem": "Outages are detected reactively after users are already affected.", "problemImpact": "Reactive detection means lost productivity agency-wide during incidents.", "impactedUsersCount": "gt_500", "targetAudience": "other", "proposedSolution": "Time-series model over infrastructure telemetry that raises early-warning alerts to the NOC. Humans triage and act.", "businessValue": "Fewer user-impacting outages; faster mean-time-to-mitigate.", "costSavings": "250k_1m", "usptoFocusArea": ["ai_infrastructure", "goal_employee_experience"], "successMetrics": "User-impacting incident count; lead time on early warnings; false-alert rate.", "timelineForResults": "6_12", "implementationComplexity": "high", "involvesSensitiveData": "no", "aiModelSourcing": "open_source_us", "aiDecisionalImpact": "no", "aiHumanReview": "yes", "readinessScore": "needs_work", "readinessSummary": "Valuable but the highest-complexity item; needs a baseline incident rate and a false-alert tolerance before committing.", "executiveSummary": "USPTO detects network outages reactively, after users are hit. A predictive model over telemetry would give the NOC early warnings to act on. High complexity; needs a baseline incident rate and an agreed false-alert tolerance.", "comments": [{"id": "c-ocio-out-1", "authorName": "Jonathan Moody", "authorRole": "reviewer", "body": "Strong upside but this is the most complex one in the queue. Before I score it: what''s the current user-impacting incident baseline, and what false-alert rate would ops actually tolerate? Need those to judge feasibility.", "createdAt": "2026-05-31T16:00:00Z"}], "reviewStatus": "needs_info"}'::jsonb, 'needs_info', 'tariq.nguyen@uspto.gov', 'ocio')
on conflict (id) do nothing;
insert into submission_comments (submission_id, author_name, author_role, body, created_at)
select 'seed-ocio-outage', 'Jonathan Moody', 'reviewer', 'Strong upside but this is the most complex one in the queue. Before I score it: what''s the current user-impacting incident baseline, and what false-alert rate would ops actually tolerate? Need those to judge feasibility.', now()
where not exists (select 1 from submission_comments where submission_id = 'seed-ocio-outage');

insert into submissions (id, submitted_at, form_data, status, owner_email, business_unit)
values ('seed-patents-autoreject', now() - interval '60 hours', '{"submitterName": "Victor Solis", "submitterEmail": "victor.solis@uspto.gov", "submitterRole": "other", "submitterOffice": "patents", "useCaseTitle": "Auto-Draft Office Action Rejections", "publicIndicator": "public", "useCaseDescription": "AI that drafts and issues 102/103 rejections automatically based on retrieved prior art.", "coreProblem": "Writing office actions takes examiner time.", "problemImpact": "Office-action drafting is a large share of examiner workload.", "impactedUsersCount": "gt_500", "targetAudience": "patent_examiner", "proposedSolution": "LLM retrieves prior art and issues the rejection directly to applicants to save examiner time.", "businessValue": "Faster office actions.", "costSavings": "gt_1m", "usptoFocusArea": ["goal_pendency_quality"], "successMetrics": "Office actions per examiner per period.", "timelineForResults": "6_12", "implementationComplexity": "high", "involvesSensitiveData": "no", "aiModelSourcing": "unknown", "aiDecisionalImpact": "yes", "aiHumanReview": "no", "readinessScore": "early_stage", "readinessSummary": "Rejected: the AI would make a patentability determination affecting applicants with no mandatory human review — outside policy. Reframe as examiner-assist with the examiner as decision-maker.", "executiveSummary": "This proposes AI that drafts and issues 102/103 rejections directly, making a patentability determination affecting applicants with no human in the loop. That crosses the decisional-AI line without mandatory human review and was declined. A reframed examiner-assist version (examiner decides) would be reconsidered.", "reviewStatus": "rejected"}'::jsonb, 'rejected', 'victor.solis@uspto.gov', 'patents')
on conflict (id) do nothing;

insert into submissions (id, submitted_at, form_data, status, owner_email, business_unit)
values ('seed-hr-resume', now() - interval '80 hours', '{"submitterName": "Bianca Lowe", "submitterEmail": "bianca.lowe@uspto.gov", "submitterRole": "manager", "submitterOffice": "hr", "useCaseTitle": "Resume Screening AI for Hiring", "publicIndicator": "public", "useCaseDescription": "AI that scores and ranks applicants and auto-rejects the bottom tier to reduce HR screening load.", "coreProblem": "HR spends significant time screening high applicant volumes.", "problemImpact": "High-volume postings generate large screening workloads.", "impactedUsersCount": "10_50", "targetAudience": "other", "proposedSolution": "Model scores resumes and auto-rejects low scorers before a human reviews them.", "businessValue": "Less screening time.", "costSavings": "50k_250k", "usptoFocusArea": ["goal_employee_experience"], "successMetrics": "Screening hours saved.", "timelineForResults": "3_6", "implementationComplexity": "medium", "involvesSensitiveData": "yes", "aiModelSourcing": "unknown", "aiDecisionalImpact": "yes", "aiHumanReview": "no", "readinessScore": "early_stage", "readinessSummary": "Rejected: auto-rejecting candidates is a decisional use affecting individuals, involves PII, and carries significant bias/EEO risk with no human review. Not appropriate for adoption as scoped.", "executiveSummary": "This proposes AI that auto-rejects job candidates before any human review — a decisional use affecting individuals, involving PII, with substantial bias and EEO exposure and no human in the loop. Declined as scoped. A human-in-the-loop assistive version would need legal/EEO review before reconsideration.", "reviewStatus": "rejected"}'::jsonb, 'rejected', 'bianca.lowe@uspto.gov', 'hr')
on conflict (id) do nothing;
