-- LaunchPad — 4 seeded submissions owned by submitter@uspto.gov (USPTO Submitter,
-- IT Staff / Trademarks). Statuses: 2 submitted, 1 needs_info (with reviewer comment),
-- 1 approved. The 5th 'in progress' item is a browser draft, created live (see runbook).
-- Idempotent. Run after 0001-0004.

insert into submissions (id, submitted_at, form_data, status, owner_email, business_unit)
values ('seed-uspto-sub-status', now() - interval '6 hours', '{"submitterName": "USPTO Submitter", "submitterEmail": "submitter@uspto.gov", "submitterRole": "it_staff", "submitterOffice": "trademarks", "publicIndicator": "public", "targetAudience": "other", "assignedReviewerName": "Matt Shankle", "assignedReviewerEmail": "matt.shankle@uspto.gov", "useCaseTitle": "Trademark Application Status Assistant", "useCaseDescription": "A cited chatbot that answers applicant questions about filing status and next steps from TSDR data and the FAQ, and escalates anything substantive to a human.", "coreProblem": "The Trademark Assistance Center is flooded with routine ''where is my application'' calls; status info is scattered across TSDR and applicants don''t know where to look.", "problemImpact": "A large share of TAC call volume is repetitive status questions that pull staff off higher-value help.", "impactedUsersCount": "gt_500", "proposedSolution": "RAG chatbot over TSDR status data and trademark FAQ; cited answers; human escalation on anything beyond status.", "businessValue": "Deflects routine status inquiries so TAC staff focus on substantive applicant help; faster answers for applicants.", "costSavings": "50k_250k", "usptoFocusArea": ["goal_employee_experience", "goal_pendency_quality"], "successMetrics": "TAC call deflection rate; median time-to-answer; applicant satisfaction.", "timelineForResults": "3_6", "implementationComplexity": "low", "involvesSensitiveData": "no", "aiModelSourcing": "american", "aiDecisionalImpact": "no", "aiHumanReview": "yes", "readinessScore": "needs_work", "readinessSummary": "Solid deflection case; needs a measured baseline for current status-call volume before scoring.", "executiveSummary": "Applicants generate heavy routine status-call volume at the Trademark Assistance Center. A cited chatbot over TSDR status and FAQ would deflect those and escalate substantive questions to staff. Needs a current call-volume baseline.", "reviewStatus": "submitted"}'::jsonb, 'submitted', 'submitter@uspto.gov', 'trademarks')
on conflict (id) do nothing;

insert into submissions (id, submitted_at, form_data, status, owner_email, business_unit)
values ('seed-uspto-sub-teas', now() - interval '30 hours', '{"submitterName": "USPTO Submitter", "submitterEmail": "submitter@uspto.gov", "submitterRole": "it_staff", "submitterOffice": "trademarks", "publicIndicator": "public", "targetAudience": "other", "assignedReviewerName": "Matt Shankle", "assignedReviewerEmail": "matt.shankle@uspto.gov", "useCaseTitle": "Automated TEAS Submission Validator", "useCaseDescription": "A pre-submission validator that flags likely errors and missing items in a trademark e-filing before it is filed, so applicants fix them up front.", "coreProblem": "Trademark e-filings come in with avoidable errors (wrong class, bad specimen, missing fields) that bounce back and add pendency and examiner rework.", "problemImpact": "Avoidable filing errors drive office actions and rework, lengthening trademark pendency.", "impactedUsersCount": "gt_500", "proposedSolution": "Validation model that checks a draft TEAS submission against common error patterns and class rules and flags issues with an explanation; applicant corrects and files clean.", "businessValue": "Fewer rejected or deficient filings, less examiner rework, lower pendency.", "costSavings": "250k_1m", "usptoFocusArea": ["goal_pendency_quality"], "successMetrics": "Filing error rate; office actions tied to filing defects; examiner rework hours.", "timelineForResults": "6_12", "implementationComplexity": "medium", "involvesSensitiveData": "no", "aiModelSourcing": "open_source_us", "aiDecisionalImpact": "no", "aiHumanReview": "yes", "readinessScore": "ready", "readinessSummary": "Strong pendency-and-quality case with a clear measurable outcome. Examiner-in-the-loop; American-built/open-source U.S.-hosted model.", "executiveSummary": "Trademark e-filings arrive with avoidable errors that bounce back and add pendency. A pre-submission validator flags likely errors and missing items so applicants file clean. Directly supports pendency and quality, with a measurable error-rate outcome.", "reviewStatus": "submitted"}'::jsonb, 'submitted', 'submitter@uspto.gov', 'trademarks')
on conflict (id) do nothing;

insert into submissions (id, submitted_at, form_data, status, owner_email, business_unit)
values ('seed-uspto-sub-ittriage', now() - interval '50 hours', '{"submitterName": "USPTO Submitter", "submitterEmail": "submitter@uspto.gov", "submitterRole": "it_staff", "submitterOffice": "trademarks", "publicIndicator": "public", "targetAudience": "other", "assignedReviewerName": "Matt Shankle", "assignedReviewerEmail": "matt.shankle@uspto.gov", "useCaseTitle": "AI Triage for Trademark IT Support Tickets", "useCaseDescription": "A classifier that categorizes, prioritizes, and routes inbound Trademarks IT support tickets, sending low-confidence ones to a human triage agent.", "coreProblem": "The Trademarks IT support queue is slow: tickets sit unclassified and get misrouted, delaying resolution for staff.", "problemImpact": "Misrouted and unclassified tickets add days to resolution and tie up tier-1 staff on sorting.", "impactedUsersCount": "50_500", "proposedSolution": "Text classifier over historical tickets that predicts category, priority, and team; auto-routes high-confidence tickets and flags the rest for human triage.", "businessValue": "Faster resolution and freed tier-1 capacity for complex cases.", "costSavings": "50k_250k", "usptoFocusArea": ["goal_employee_experience"], "successMetrics": "Ticket-to-resolution time; misroute rate; tier-1 time on routine sorting.", "timelineForResults": "3_6", "implementationComplexity": "low", "involvesSensitiveData": "no", "aiModelSourcing": "unknown", "aiDecisionalImpact": "no", "aiHumanReview": "yes", "readinessScore": "needs_work", "readinessSummary": "Good operational fit, but model sourcing is unconfirmed and there is no current baseline for resolution time.", "executiveSummary": "Trademarks IT tickets sit unclassified and get misrouted, slowing resolution. A classifier would predict category, priority, and team and auto-route high-confidence tickets. Needs a resolution-time baseline and confirmed model sourcing.", "reviewStatus": "needs_info", "comments": [{"id": "c-uspto-it-1", "authorName": "Matt Shankle", "authorRole": "reviewer", "body": "Good fit for the queue. Before I can score it, two things: what''s the current ticket-to-resolution baseline, and can you confirm the model sourcing? It''s marked unknown, which is a blocker under the EO.", "createdAt": "2026-06-04T14:00:00Z"}]}'::jsonb, 'needs_info', 'submitter@uspto.gov', 'trademarks')
on conflict (id) do nothing;
insert into submission_comments (submission_id, author_name, author_role, body, created_at)
select 'seed-uspto-sub-ittriage', 'Matt Shankle', 'reviewer', 'Good fit for the queue. Before I can score it, two things: what''s the current ticket-to-resolution baseline, and can you confirm the model sourcing? It''s marked unknown, which is a blocker under the EO.', now()
where not exists (select 1 from submission_comments where submission_id = 'seed-uspto-sub-ittriage');

insert into submissions (id, submitted_at, form_data, status, owner_email, business_unit)
values ('seed-uspto-sub-idmanual', now() - interval '120 hours', '{"submitterName": "USPTO Submitter", "submitterEmail": "submitter@uspto.gov", "submitterRole": "it_staff", "submitterOffice": "trademarks", "publicIndicator": "public", "targetAudience": "other", "assignedReviewerName": "Matt Shankle", "assignedReviewerEmail": "matt.shankle@uspto.gov", "useCaseTitle": "Trademark ID Manual Smart Search", "useCaseDescription": "Semantic search over the Acceptable Identification of Goods and Services Manual that returns ranked suggested identifications with class for an examiner or applicant to pick.", "coreProblem": "Examiners and applicants struggle to find the right entries in the ID Manual with keyword search, leading to inconsistent identifications.", "problemImpact": "Hard-to-search IDs cause inconsistent identifications and identification-related office actions.", "impactedUsersCount": "50_500", "proposedSolution": "Embedding-based search over the ID Manual returning ranked suggested IDs with class; the user selects. No automated determination.", "businessValue": "Faster, more consistent ID selection; fewer office actions tied to identification.", "costSavings": "50k_250k", "usptoFocusArea": ["goal_pendency_quality"], "successMetrics": "Time to select an ID; identification-related office action rate; suggestion acceptance rate.", "timelineForResults": "3_6", "implementationComplexity": "low", "involvesSensitiveData": "no", "aiModelSourcing": "open_source_us", "aiDecisionalImpact": "no", "aiHumanReview": "yes", "readinessScore": "ready", "readinessSummary": "Low-risk, well-scoped, measurable, American-built/open-source U.S.-hosted, user-in-the-loop. Approved.", "executiveSummary": "Keyword search over the Trademark ID Manual makes the right identifications hard to find, driving inconsistency. Semantic search returns ranked suggested IDs for the user to pick. Low risk, measurable, examiner-in-the-loop.", "reviewStatus": "approved"}'::jsonb, 'approved', 'submitter@uspto.gov', 'trademarks')
on conflict (id) do nothing;
