-- LaunchPad DoW seed: command reviewers, submitter accounts, and Army-themed
-- submissions across all statuses. Run after dow/0000 + 0001. Demo password: 'launchpad'.
-- Idempotent (guarded inserts).

-- Reviewers (one per command) -------------------------------------------
insert into users (id,email,name,role,password,job_role,business_unit,created_at)
select 'user-dana-reyes','dana.reyes@army.mil','MAJ Dana Reyes','reviewer','launchpad',null,'forscom',now()
where not exists (select 1 from users where email='dana.reyes@army.mil');
insert into users (id,email,name,role,password,job_role,business_unit,created_at)
select 'user-paul-whitfield','paul.whitfield@army.mil','Paul Whitfield','reviewer','launchpad',null,'amc',now()
where not exists (select 1 from users where email='paul.whitfield@army.mil');
insert into users (id,email,name,role,password,job_role,business_unit,created_at)
select 'user-sandra-boyd','sandra.boyd@army.mil','LTC Sandra Boyd','reviewer','launchpad',null,'tradoc',now()
where not exists (select 1 from users where email='sandra.boyd@army.mil');
insert into users (id,email,name,role,password,job_role,business_unit,created_at)
select 'user-alan-pierce','alan.pierce@army.mil','Dr. Alan Pierce','reviewer','launchpad',null,'afc',now()
where not exists (select 1 from users where email='alan.pierce@army.mil');
insert into users (id,email,name,role,password,job_role,business_unit,created_at)
select 'user-maria-santos','maria.santos@army.mil','COL Maria Santos','reviewer','launchpad',null,'medcom',now()
where not exists (select 1 from users where email='maria.santos@army.mil');
insert into users (id,email,name,role,password,job_role,business_unit,created_at)
select 'user-derek-hsu','derek.hsu@army.mil','CW4 Derek Hsu','reviewer','launchpad',null,'arcyber',now()
where not exists (select 1 from users where email='derek.hsu@army.mil');
insert into users (id,email,name,role,password,job_role,business_unit,created_at)
select 'user-karen-udall','karen.udall@army.mil','Karen Udall','reviewer','launchpad',null,'sustainment',now()
where not exists (select 1 from users where email='karen.udall@army.mil');

-- Submitters -------------------------------------------------------------
insert into users (id,email,name,role,password,job_role,business_unit,created_at)
select 'user-submitter','submitter@army.mil','Army Submitter','submitter','launchpad','it_staff','sustainment',now()
where not exists (select 1 from users where email='submitter@army.mil');
insert into users (id,email,name,role,password,job_role,business_unit,created_at)
select 'user-marcus-bell','marcus.bell@army.mil','SSG Marcus Bell','submitter','launchpad','other','amc',now()
where not exists (select 1 from users where email='marcus.bell@army.mil');
insert into users (id,email,name,role,password,job_role,business_unit,created_at)
select 'user-elena-ruiz','elena.ruiz@army.mil','CPT Elena Ruiz','submitter','launchpad','manager','forscom',now()
where not exists (select 1 from users where email='elena.ruiz@army.mil');
insert into users (id,email,name,role,password,job_role,business_unit,created_at)
select 'user-victor-kane','victor.kane@army.mil','Victor Kane','submitter','launchpad','it_staff','arcyber',now()
where not exists (select 1 from users where email='victor.kane@army.mil');
insert into users (id,email,name,role,password,job_role,business_unit,created_at)
select 'user-priya-anand','priya.anand@army.mil','MAJ Priya Anand','submitter','launchpad','other','medcom',now()
where not exists (select 1 from users where email='priya.anand@army.mil');
insert into users (id,email,name,role,password,job_role,business_unit,created_at)
select 'user-linda-park','linda.park@army.mil','Linda Park','submitter','launchpad','manager','tradoc',now()
where not exists (select 1 from users where email='linda.park@army.mil');
insert into users (id,email,name,role,password,job_role,business_unit,created_at)
select 'user-owen-tate','owen.tate@army.mil','Owen Tate','submitter','launchpad','other','afc',now()
where not exists (select 1 from users where email='owen.tate@army.mil');

-- Submissions -----------------------------------------------------------
insert into submissions (id,submitted_at,form_data,status,owner_email,business_unit)
values ('dow-amc-pdm', now() - interval '6 hours', '{"submitterName": "SSG Marcus Bell", "submitterEmail": "marcus.bell@army.mil", "submitterRole": "other", "submitterOffice": "amc", "publicIndicator": "public", "targetAudience": "other", "assignedReviewerName": "Paul Whitfield", "assignedReviewerEmail": "paul.whitfield@army.mil", "useCaseTitle": "Predictive Maintenance for Ground Combat Vehicles", "useCaseDescription": "A model that predicts component failures on Bradley and Abrams platforms from maintenance and sensor data so units schedule repairs before a deadline, not after a breakdown.", "coreProblem": "Unscheduled vehicle deadlines drive readiness down; maintenance is reactive and parts arrive late.", "problemImpact": "Deadlined vehicles directly reduce unit readiness ratings and training throughput.", "impactedUsersCount": "gt_500", "proposedSolution": "ML over historical maintenance and telemetry predicting likely failures with lead time; maintainers schedule the work. No automated action.", "businessValue": "Higher operational readiness rates and fewer mission-impacting deadlines; smoother parts demand.", "costSavings": "gt_1m", "usptoFocusArea": ["adopt_advantage", "adopt_data"], "successMetrics": "Operational readiness rate; unscheduled deadline count; mean time to repair.", "timelineForResults": "6_12", "implementationComplexity": "medium", "involvesSensitiveData": "no", "aiModelSourcing": "open_source_us", "aiDecisionalImpact": "no", "aiHumanReview": "yes", "readinessScore": "ready", "readinessSummary": "Strong readiness case with a measurable outcome, maintainer-in-the-loop, American-built model. Ready for review.", "executiveSummary": "Unscheduled vehicle deadlines pull down unit readiness. A predictive-maintenance model over maintenance and telemetry data gives maintainers failure lead time to schedule repairs proactively. Measurable readiness outcome; human-in-the-loop; American-built.", "reviewStatus": "in_review"}'::jsonb, 'in_review', 'marcus.bell@army.mil', 'amc')
on conflict (id) do nothing;

insert into submissions (id,submitted_at,form_data,status,owner_email,business_unit)
values ('dow-sus-forecast', now() - interval '26 hours', '{"submitterName": "Army Submitter", "submitterEmail": "submitter@army.mil", "submitterRole": "it_staff", "submitterOffice": "sustainment", "publicIndicator": "public", "targetAudience": "other", "assignedReviewerName": "Karen Udall", "assignedReviewerEmail": "karen.udall@army.mil", "useCaseTitle": "AI-Assisted Demand Forecasting for Repair Parts", "useCaseDescription": "Forecasts repair-part demand by unit and region so the supply chain pre-positions stock instead of reacting to back-orders.", "coreProblem": "Repair-part demand is forecast with simple averages; high-demand parts back-order and stall maintenance.", "problemImpact": "Back-ordered parts extend vehicle and equipment downtime across sustainment.", "impactedUsersCount": "gt_500", "proposedSolution": "Time-series demand model by NSN, unit, and region; planners use it to set stock levels. Recommendation only.", "businessValue": "Fewer back-orders, shorter downtime, less excess stock.", "costSavings": "250k_1m", "usptoFocusArea": ["adopt_data", "adopt_advantage"], "successMetrics": "Back-order rate; fill rate; days of equipment downtime attributable to parts.", "timelineForResults": "6_12", "implementationComplexity": "medium", "involvesSensitiveData": "no", "aiModelSourcing": "open_source_us", "aiDecisionalImpact": "no", "aiHumanReview": "yes", "readinessScore": "needs_work", "readinessSummary": "Good sustainment fit; needs a measured baseline for current back-order and fill rates before scoring.", "executiveSummary": "Repair-part demand is forecast crudely, so high-demand parts back-order and stall maintenance. A demand-forecasting model would let planners pre-position stock. Needs a current back-order/fill-rate baseline.", "reviewStatus": "submitted"}'::jsonb, 'submitted', 'submitter@army.mil', 'sustainment')
on conflict (id) do nothing;

insert into submissions (id,submitted_at,form_data,status,owner_email,business_unit)
values ('dow-forscom-readiness', now() - interval '50 hours', '{"submitterName": "CPT Elena Ruiz", "submitterEmail": "elena.ruiz@army.mil", "submitterRole": "manager", "submitterOffice": "forscom", "publicIndicator": "public", "targetAudience": "other", "assignedReviewerName": "MAJ Dana Reyes", "assignedReviewerEmail": "dana.reyes@army.mil", "useCaseTitle": "Unit Readiness Reporting Anomaly Detection", "useCaseDescription": "Flags inconsistent or anomalous unit readiness reports for a human review before they roll up to higher echelons.", "coreProblem": "Readiness reports contain data-entry errors and inconsistencies that distort the readiness picture at echelon.", "problemImpact": "Bad readiness data leads to misinformed sourcing and resourcing decisions.", "impactedUsersCount": "50_500", "proposedSolution": "Anomaly model over historical readiness submissions; flags outliers and likely errors for an S-3 to verify. No automated correction.", "businessValue": "A cleaner, more trustworthy readiness picture for commanders.", "costSavings": "50k_250k", "usptoFocusArea": ["adopt_advantage", "rai_traceable"], "successMetrics": "Error/correction rate caught pre-rollup; analyst time on data cleanup.", "timelineForResults": "3_6", "implementationComplexity": "low", "involvesSensitiveData": "no", "aiModelSourcing": "unknown", "aiDecisionalImpact": "no", "aiHumanReview": "yes", "readinessScore": "needs_work", "readinessSummary": "Useful and low-risk, but model sourcing is unconfirmed and there is no baseline error rate.", "executiveSummary": "Readiness reports carry errors that distort the picture at echelon. An anomaly detector would flag likely errors for an S-3 to verify before rollup. Needs a baseline error rate and confirmed model sourcing.", "comments": [{"id": "c-dow-fc-1", "authorName": "MAJ Dana Reyes", "authorRole": "reviewer", "body": "Worth pursuing. Two things before I can score it: what''s the current error rate we''d be catching, and confirm the model sourcing -- it''s marked unknown, which we can''t accept under the AI Ethical Principles guidance.", "createdAt": "2026-06-05T14:00:00Z"}], "reviewStatus": "needs_info"}'::jsonb, 'needs_info', 'elena.ruiz@army.mil', 'forscom')
on conflict (id) do nothing;
insert into submission_comments (submission_id,author_name,author_role,body,created_at)
select 'dow-forscom-readiness','MAJ Dana Reyes','reviewer','Worth pursuing. Two things before I can score it: what''s the current error rate we''d be catching, and confirm the model sourcing -- it''s marked unknown, which we can''t accept under the AI Ethical Principles guidance.',now()
where not exists (select 1 from submission_comments where submission_id='dow-forscom-readiness');

insert into submissions (id,submitted_at,form_data,status,owner_email,business_unit)
values ('dow-arcyber-phish', now() - interval '90 hours', '{"submitterName": "Victor Kane", "submitterEmail": "victor.kane@army.mil", "submitterRole": "it_staff", "submitterOffice": "arcyber", "publicIndicator": "public", "targetAudience": "other", "assignedReviewerName": "CW4 Derek Hsu", "assignedReviewerEmail": "derek.hsu@army.mil", "useCaseTitle": "Phishing Email Triage Assistant", "useCaseDescription": "Classifies reported suspicious emails by threat type and severity and routes them, so analysts focus on real threats instead of sorting.", "coreProblem": "The reported-phishing queue is large and mostly benign; analysts spend time sorting instead of hunting.", "problemImpact": "Slow triage means real phishing campaigns are confirmed later than they should be.", "impactedUsersCount": "gt_500", "proposedSolution": "Classifier over reported emails predicting threat type and severity; auto-routes high-confidence, flags the rest for an analyst.", "businessValue": "Faster confirmation of real campaigns; analyst time freed for hunting.", "costSavings": "250k_1m", "usptoFocusArea": ["adopt_advantage", "rai_reliable"], "successMetrics": "Time-to-confirm a real campaign; analyst hours on triage; false-clear rate.", "timelineForResults": "3_6", "implementationComplexity": "low", "involvesSensitiveData": "no", "aiModelSourcing": "open_source_us", "aiDecisionalImpact": "no", "aiHumanReview": "yes", "readinessScore": "ready", "readinessSummary": "Low-risk, measurable, American-built, analyst-in-the-loop. Approved.", "executiveSummary": "The reported-phishing queue is mostly benign, slowing confirmation of real campaigns. A classifier triages and routes by threat and severity, keeping analysts on hunting. Low risk, measurable, human-in-the-loop.", "reviewStatus": "approved"}'::jsonb, 'approved', 'victor.kane@army.mil', 'arcyber')
on conflict (id) do nothing;

insert into submissions (id,submitted_at,form_data,status,owner_email,business_unit)
values ('dow-medcom-notes', now() - interval '70 hours', '{"submitterName": "MAJ Priya Anand", "submitterEmail": "priya.anand@army.mil", "submitterRole": "other", "submitterOffice": "medcom", "publicIndicator": "public", "targetAudience": "other", "assignedReviewerName": "COL Maria Santos", "assignedReviewerEmail": "maria.santos@army.mil", "useCaseTitle": "Clinical Note Summarization for Army Medicine", "useCaseDescription": "Drafts a structured summary of a patient encounter for a provider to review and sign, reducing documentation time.", "coreProblem": "Providers spend hours on documentation, reducing time with patients.", "problemImpact": "Documentation burden contributes to provider burnout and lower throughput.", "impactedUsersCount": "50_500", "proposedSolution": "Summarization model that drafts a structured note from the encounter; the provider edits and signs. Never finalizes on its own.", "businessValue": "Less documentation time, more patient face time.", "costSavings": "250k_1m", "usptoFocusArea": ["adopt_advantage", "rai_traceable"], "successMetrics": "Documentation minutes per encounter; provider-edit rate; patient throughput.", "timelineForResults": "6_12", "implementationComplexity": "medium", "involvesSensitiveData": "yes", "aiModelSourcing": "american", "aiDecisionalImpact": "no", "aiHumanReview": "yes", "readinessScore": "needs_work", "readinessSummary": "Promising, but it involves PHI/CUI -- the data classification and handling controls (Impact Level, access controls) must be specified before it can be scored.", "executiveSummary": "Providers spend hours documenting. A summarization model would draft a structured note for the provider to edit and sign. Because it touches PHI/CUI, the classification, Impact Level, and access controls must be defined before scoring.", "comments": [{"id": "c-dow-med-1", "authorName": "COL Maria Santos", "authorRole": "reviewer", "body": "Strong value. This touches PHI, so before scoring I need the data classification and Impact Level you''re targeting and the access-control plan. Spell those out and resubmit.", "createdAt": "2026-06-05T15:00:00Z"}], "reviewStatus": "needs_info"}'::jsonb, 'needs_info', 'priya.anand@army.mil', 'medcom')
on conflict (id) do nothing;
insert into submission_comments (submission_id,author_name,author_role,body,created_at)
select 'dow-medcom-notes','COL Maria Santos','reviewer','Strong value. This touches PHI, so before scoring I need the data classification and Impact Level you''re targeting and the access-control plan. Spell those out and resubmit.',now()
where not exists (select 1 from submission_comments where submission_id='dow-medcom-notes');

insert into submissions (id,submitted_at,form_data,status,owner_email,business_unit)
values ('dow-tradoc-training', now() - interval '34 hours', '{"submitterName": "Linda Park", "submitterEmail": "linda.park@army.mil", "submitterRole": "manager", "submitterOffice": "tradoc", "publicIndicator": "public", "targetAudience": "other", "assignedReviewerName": "LTC Sandra Boyd", "assignedReviewerEmail": "sandra.boyd@army.mil", "useCaseTitle": "Adaptive Training Content Recommender", "useCaseDescription": "Recommends the next training module to a soldier based on performance and role, so training adapts instead of being one-size-fits-all.", "coreProblem": "Training is largely fixed-sequence; soldiers repeat mastered material and under-train weak areas.", "problemImpact": "Inefficient training time and uneven proficiency across a unit.", "impactedUsersCount": "gt_500", "proposedSolution": "Recommender over performance and role data suggesting the next module; instructors approve the path.", "businessValue": "Faster proficiency, less wasted training time.", "costSavings": "50k_250k", "usptoFocusArea": ["adopt_talent"], "successMetrics": "Time-to-proficiency; assessment pass rates; training hours per competency.", "timelineForResults": "6_12", "implementationComplexity": "medium", "involvesSensitiveData": "no", "aiModelSourcing": "open_source_us", "aiDecisionalImpact": "no", "aiHumanReview": "yes", "readinessScore": "needs_work", "readinessSummary": "Reasonable talent-development case; needs a baseline time-to-proficiency and an instructor-approval step defined.", "executiveSummary": "Fixed-sequence training wastes time on mastered material. A recommender would adapt the next module to performance and role, with instructor approval. Needs a time-to-proficiency baseline.", "reviewStatus": "submitted"}'::jsonb, 'submitted', 'linda.park@army.mil', 'tradoc')
on conflict (id) do nothing;

insert into submissions (id,submitted_at,form_data,status,owner_email,business_unit)
values ('dow-afc-targeting', now() - interval '120 hours', '{"submitterName": "Owen Tate", "submitterEmail": "owen.tate@army.mil", "submitterRole": "other", "submitterOffice": "afc", "publicIndicator": "public", "targetAudience": "other", "assignedReviewerName": "Dr. Alan Pierce", "assignedReviewerEmail": "alan.pierce@army.mil", "useCaseTitle": "Automated Target Recognition and Engagement from ISR Imagery", "useCaseDescription": "Detects and classifies targets in ISR imagery and cues engagement automatically to reduce the sensor-to-shooter timeline.", "coreProblem": "The sensor-to-shooter timeline is too slow for time-sensitive targets.", "problemImpact": "Slow timelines mean missed engagement windows.", "impactedUsersCount": "50_500", "proposedSolution": "Computer-vision model that detects and classifies targets and automatically cues engagement.", "businessValue": "Faster sensor-to-shooter.", "costSavings": "gt_1m", "usptoFocusArea": ["adopt_advantage", "rai_governable"], "successMetrics": "Sensor-to-shooter time.", "timelineForResults": "12+", "implementationComplexity": "high", "involvesSensitiveData": "no", "aiModelSourcing": "unknown", "aiDecisionalImpact": "yes", "aiHumanReview": "no", "readinessScore": "early_stage", "readinessSummary": "Rejected as scoped: the AI would make an engagement determination with no mandatory human review -- contrary to the DoD AI Ethical Principles (Responsible, Governable) and human-judgment policy. Reframe as a decision-support / detection aid with a human in the loop and resubmit.", "executiveSummary": "This proposes AI that detects targets and automatically cues engagement with no human in the loop -- a lethal decision made by the system. That is contrary to the DoD AI Ethical Principles and human-judgment requirements, so it was declined as scoped. A detection / decision-support version with mandatory human review would be reconsidered.", "reviewStatus": "rejected"}'::jsonb, 'rejected', 'owen.tate@army.mil', 'afc')
on conflict (id) do nothing;

insert into submissions (id,submitted_at,form_data,status,owner_email,business_unit)
values ('dow-sus-motorpool', now() - interval '10 hours', '{"submitterName": "Army Submitter", "submitterEmail": "submitter@army.mil", "submitterRole": "it_staff", "submitterOffice": "sustainment", "publicIndicator": "public", "targetAudience": "other", "assignedReviewerName": "Karen Udall", "assignedReviewerEmail": "karen.udall@army.mil", "useCaseTitle": "Motor Pool Work-Order Auto-Routing", "useCaseDescription": "Classifies and routes incoming motor-pool work orders to the right shop and priority so jobs stop sitting unassigned.", "coreProblem": "Work orders sit unassigned and get misrouted, delaying vehicle services.", "problemImpact": "Misrouted work orders add days to services and reduce availability.", "impactedUsersCount": "50_500", "proposedSolution": "Classifier predicting shop, priority, and parts need; auto-routes high-confidence, flags the rest for the dispatcher.", "businessValue": "Faster services, higher vehicle availability.", "costSavings": "50k_250k", "usptoFocusArea": ["adopt_advantage"], "successMetrics": "Work-order cycle time; misroute rate; vehicle availability.", "timelineForResults": "3_6", "implementationComplexity": "low", "involvesSensitiveData": "no", "aiModelSourcing": "open_source_us", "aiDecisionalImpact": "no", "aiHumanReview": "yes", "readinessScore": "needs_work", "readinessSummary": "Clean operational fit; needs a current work-order cycle-time baseline.", "executiveSummary": "Motor-pool work orders sit unassigned and get misrouted, delaying services. A classifier would route by shop and priority, dispatcher-in-the-loop. Needs a cycle-time baseline.", "reviewStatus": "submitted"}'::jsonb, 'submitted', 'submitter@army.mil', 'sustainment')
on conflict (id) do nothing;
