// Army CPE ES2 demo seed — the deterministic "golden state" the admin Demo
// Data reset restores. Used when NEXT_PUBLIC_TENANT=es2. Mirrors the shape of
// lib/seedSubmissionsDoc.ts, spanning the five ES2 program offices (AT&R,
// HR-FM, LOG-FIN, BTS, C-ERP) and, under AT&R, its four programs (ACWS, ATIS,
// FMS-ACES, Digital Market).
//
// This is a demo script, not sample data. Two mechanisms have to fire, and
// they are mutually exclusive by design, so they need separate groups:
//
//   - CROSS-PROGRAM DUPLICATES (items 10-12). `isCrossBureauDuplicatePair`
//     (lib/crossBureauDuplicates.ts) needs a different business_unit, a
//     `similarity()` at or above 0.25, AND no shared lib/ombConsolidation.ts
//     category. `similarity()` is Jaccard token overlap over the four
//     "what is this" fields only (title, coreProblem, proposedSolution,
//     useCaseDescription) — lexical, not semantic — so these three are written
//     to share heavy vocabulary (vendor/supplier, past performance, award,
//     risk, score, delivery, history, protest, source selection) while reading
//     as three teams who each independently had the same idea. Vendor
//     past-performance scoring was chosen precisely because no consolidation
//     regex covers it; lib/seedSubmissionsEs2.test.ts asserts that, since it
//     is the assertion that catches the design error.
//   - CONSOLIDATION (items 13-14). Both match the "meeting_transcription"
//     category and collapse into one inventory row. Because they share a
//     category they are excluded from duplicate detection — which is the
//     point of keeping the two groups apart.
//
// LIFECYCLE COMPLETENESS (issue #164's two-stage model): governance fields are
// completed during vetting, not at intake, and the seed shows that.
//   draft / submitted     -> intake fields only; stageOfDevelopment,
//                            highImpact, hasATO, systemSource and the RMF
//                            inputs are deliberately empty. These are ideas.
//   in_review / needs_info -> intake plus partial governance, so the
//                            reviewer's checklist has visible work left.
//   approved / rejected    -> intake plus governance complete, sign-off
//                            recorded.
//
// Every id, email and `hoursAgo(n)` offset is deterministic on purpose: the
// admin "Reset Demo Data" button wipes and re-inserts this exact array. The
// submitter emails must stay in step with db/migrations/es2/0001_es2_users_seed.sql
// or the reviewer views come up empty — asserted in the test.
//
// submitterOffice values are program-office codes from lib/tenant/es2.ts;
// submitterSubOffice values are AT&R program codes. Both render through
// getTenant().unit.options, so a raw code never reaches a screen.

import type { FormData } from "@/lib/steps"
import { initialFormData } from "@/lib/steps"
import { type Submission } from "@/lib/submissions"

function mk(partial: Partial<FormData>): FormData {
  return { ...initialFormData, ...partial }
}

const hoursAgo = (h: number) => new Date(Date.now() - 1000 * 60 * 60 * h).toISOString()

export const es2SeedSubmissions: Submission[] = [
  // 1) AT&R / ACWS — the clean win, and the seed's high-impact + deployed
  // example, so all nine M-25-21 minimum-practice fields render and RMF
  // Measure/Manage become applicable rather than not_yet_applicable.
  {
    id: "es2-acws-clause-recommendation",
    submittedAt: hoursAgo(96),
    formData: mk({
      submitterName: "Dana Whitfield",
      submitterEmail: "dana.whitfield@es2.demo",
      submitterRole: "contract_specialist",
      submitterOffice: "atr",
      submitterSubOffice: "acws",
      reviewStatus: "approved",
      bureauSignoff: {
        bureau: "atr",
        decision: "approved",
        signedOffByName: "Alan Brooks",
        signedOffByEmail: "alan.brooks@es2.demo",
        signedOffAt: hoursAgo(70),
      },
      comments: [
        {
          id: "c-acws-clause-1",
          authorName: "Alan Brooks",
          authorRole: "reviewer",
          body: "Approved. Recommendations are advisory, the specialist accepts or rejects each one, and every suggestion cites the regulation text it came from. Testing, monitoring and the appeal path are on file.",
          createdAt: hoursAgo(70),
        },
      ],
      useCaseTitle: "Clause Recommendation From Requirement Text",
      useCaseDescription:
        "Reads a requirement package and suggests the clauses a contract specialist should consider, each one citing the regulation text behind it. Advisory: the specialist accepts, edits, or rejects every suggestion before the file moves.",
      isWithheld: "no",
      targetAudience: "contract_specialist",
      impactedUsersCount: "50_500",
      painPoints:
        "Specialists hand-check clause applicability against long regulation text under deadline pressure, and a missed clause surfaces late, during review or after award.",
      targetUserContext: "Contract specialists and contracting officers building requirement packages in the contract writing system.",
      targetUserSummary: "Contract specialists assembling clause sets under deadline pressure.",
      coreProblem:
        "Clause selection is manual and depends on individual recall, so applicable clauses get missed and inconsistency shows up between offices.",
      problemImpact: "Missed or inconsistent clauses drive rework late in the cycle and weaken the file under audit.",
      affectedBusinessUnits: ["contract_writing"],
      problemType: ["quality", "productivity"],
      severity: "high",
      problemDefinition:
        "Specialists have no consistent, regulation-grounded way to see which clauses a requirement calls for before the package moves.",
      proposedSolution:
        "A retrieval-grounded recommender over current regulation text that proposes candidate clauses for a requirement package, shows the citation for each, and records what the specialist accepted or rejected. It never writes a clause into the file on its own.",
      keyFunctionality: ["question_answering", "search", "classification"],
      solutionSummary: "Regulation-grounded, cited clause recommendations that a specialist accepts or rejects.",
      deliveryAudience: "internal",
      userValue: "Specialists see the candidate clause set in seconds with the citation attached, instead of hand-checking regulation text.",
      userTimeSavings: "1_5",
      otherUserImprovements: ["more_consistent_work", "better_decisions"],
      userValueSummary: "Faster, better-cited clause selection with the decision left to the specialist.",
      businessValue: "Fewer missed clauses, less late rework, and a defensible record of why each clause was chosen.",
      costSavings: "250k_1m",
      strategicBenefit: ["operational_efficiency", "improve_quality"],
      businessValueSummary: "Cuts late rework and strengthens the contract file under audit.",
      usptoFocusArea: ["atr_contract_speed", "atr_audit_readiness"],
      relevantOkrs: "Contract action cycle time; audit readiness of the contract file; consistency across offices.",
      alignmentSummary: "Directly advances faster, more accurate contract actions and audit readiness.",
      implementationComplexity: "medium",
      resourcesNeeded: ["ml_engineers", "content_owner", "infrastructure"],
      dependencies: "Current regulation corpus with change tracking; accredited hosting boundary; acceptance logging in the contract writing system.",
      involvesSensitiveData: "no",
      securityClassification: "controlled",
      impactLevel: "cui",
      dataReadiness: "ai_ready",
      trl: "8",
      accessControlRequirements: ["employee_authentication", "audit_logging"],
      aiDecisionalImpact: "no",
      aiModelSourcing: "american_built",
      aiHumanReview: "yes",
      stageOfDevelopment: "deployed",
      highImpact: "high_impact",
      highImpactFactors: ["resource_allocation"],
      highImpactJustification:
        "Clause selection shapes the terms of an award, so the output can affect how public resources are committed even though a person makes the decision.",
      topicArea: "procurement_financial_management",
      aiClassification: "nlp",
      disseminatesToPublic: "no",
      scalable: "yes",
      hasATO: "yes",
      atoSystemName: "Contract Writing System",
      systemSource: "contract",
      operationalDate: "2026-02-01",
      trainingDataDescription: "Current regulation text plus historical clause selections, with acceptance decisions retained for evaluation.",
      hasPii: "no",
      demographicFeatures: ["none"],
      customCode: "yes",
      nationalSecuritySystem: "no",
      researchOnly: "no",
      preDeploymentTesting: "yes",
      preDeploymentTestingNote: "Evaluated against historical packages with specialist adjudication before the first office went live.",
      aiImpactAssessmentCompleted: "yes",
      aiImpactAssessment:
        "Reviewed for over-reliance on suggestions, drift as regulation text changes, and the risk of a stale corpus proposing a superseded clause. Mitigated by citation display, change tracking, and acceptance logging.",
      independentReviewConducted: "yes_other_office",
      ongoingMonitoringPlan: "yes",
      ongoingMonitoringNote: "Acceptance rate and missed-clause findings reviewed each release; corpus drift triggers a re-review.",
      operatorTrainingEstablished: "yes",
      failSafeMechanism: "yes",
      humanOversightAppeal: "yes",
      humanOversightAppealNote: "A specialist can reject any recommendation without justification, and the rejection is recorded.",
      publicConsultationSteps: ["direct_usability_testing"],
      feasibilitySummary:
        "Deployed and accredited. The bar is citation groundedness and keeping the regulation corpus current; both are monitored.",
      successMetrics: "Recommendation acceptance rate, missed-clause findings at review, cycle time per package, specialist-rated citation accuracy.",
      keyMetrics: ["quality_improvement", "time_saved", "adoption_rate"],
      timelineForResults: "6_12",
      metricsSummary: "Tracks acceptance, missed-clause findings, and cycle time against the pre-deployment baseline.",
      routeTo: ["governance"],
      reviewerNotes: "Advisory by design with citations and an accept/reject record. Minimum practices are on file.",
      readinessScore: "ready",
      readinessSummary: "Complete, accredited, and monitored. The strongest example of the pattern the enterprise wants.",
      executiveSummary:
        "Specialists hand-check clause applicability against long regulation text, and misses surface late. This deployed recommender proposes candidate clauses with the regulation citation attached and logs what the specialist accepted or rejected. Advisory only, American-built, inside the accredited boundary, with testing, monitoring and an appeal path on file.",
    } as Partial<FormData>),
  },

  // 2) AT&R / ACWS — REJECTED. Decisional AI on award outcomes with no human
  // review. Reads as a reasonable efficiency idea until the governance fields.
  {
    id: "es2-acws-source-selection-scoring",
    submittedAt: hoursAgo(120),
    formData: mk({
      submitterName: "Marcus Bell",
      submitterEmail: "marcus.bell@es2.demo",
      submitterRole: "program_manager",
      submitterOffice: "atr",
      submitterSubOffice: "acws",
      reviewStatus: "rejected",
      bureauSignoff: {
        bureau: "atr",
        decision: "rejected",
        signedOffByName: "Alan Brooks",
        signedOffByEmail: "alan.brooks@es2.demo",
        signedOffAt: hoursAgo(84),
      },
      comments: [
        {
          id: "c-acws-selection-1",
          authorName: "Alan Brooks",
          authorRole: "reviewer",
          body: "Rejected as scoped. This produces a ranked technical evaluation that the board is expected to adopt, with no mandatory human evaluation of its own and no way for an offeror to contest how the ranking was produced. Automating an award outcome without a person accountable for the evaluation is exactly what the ethical principles require us to stop. Resubmit as a decision-support aid: the board scores independently first, the tool is advisory, and the reasoning is disclosable.",
          createdAt: hoursAgo(84),
        },
      ],
      useCaseTitle: "Automated Source Selection Scoring",
      useCaseDescription:
        "Reads technical proposals, applies the stated evaluation criteria, and issues a ranked technical rating that the selection board adopts directly as the technical evaluation of record.",
      isWithheld: "no",
      targetAudience: "contracting_officer",
      impactedUsersCount: "10_50",
      painPoints:
        "Technical evaluation boards spend weeks reading proposals, ratings vary between evaluators, and a contested rating is expensive to defend.",
      targetUserContext: "Technical evaluation board members and the contracting officers who convene them.",
      targetUserSummary: "Evaluation board members working through proposal volumes under schedule pressure.",
      coreProblem:
        "Technical evaluation is slow and varies by evaluator, so the board becomes the bottleneck on an acquisition timeline.",
      problemImpact: "Evaluation timelines slip and inconsistent ratings are hard to defend when challenged.",
      affectedBusinessUnits: ["contract_writing"],
      problemType: ["productivity", "quality"],
      severity: "high",
      problemDefinition:
        "Technical evaluation of proposals is slow and inconsistent, and the board has no faster path that keeps the rating defensible.",
      proposedSolution:
        "A model that ingests each proposal, applies the stated evaluation criteria, and emits a numeric technical rating per criterion. The board adopts the rating as its technical evaluation; no separate board evaluation is performed.",
      keyFunctionality: ["classification", "ranking"],
      solutionSummary: "Model-issued technical ratings adopted as the board's evaluation of record.",
      deliveryAudience: "internal",
      userValue: "Board members would get through proposal volumes far faster.",
      userTimeSavings: "5_10",
      otherUserImprovements: ["more_consistent_work"],
      userValueSummary: "Much faster evaluation, at the cost of the board's own judgment.",
      businessValue: "Would shorten acquisition timelines, but not in a form that survives a challenge.",
      costSavings: "250k_1m",
      strategicBenefit: ["operational_efficiency"],
      businessValueSummary: "Timeline gain does not justify an unaccountable evaluation of record.",
      usptoFocusArea: ["atr_acquisition_efficiency"],
      relevantOkrs: "Acquisition timeline; evaluation consistency; defensibility of the evaluation record.",
      alignmentSummary: "The efficiency goal is real; the design conflicts with the human-judgment and traceability principles.",
      implementationComplexity: "medium",
      resourcesNeeded: ["ml_engineers", "infrastructure"],
      dependencies: "Historical proposal and rating data; an evaluation workflow that currently has no place for a person to override.",
      involvesSensitiveData: "yes",
      securityClassification: "controlled",
      impactLevel: "cui",
      dataReadiness: "partial",
      trl: "4",
      accessControlRequirements: ["employee_authentication", "audit_logging"],
      aiDecisionalImpact: "yes",
      aiModelSourcing: "american_built",
      aiHumanReview: "no",
      stageOfDevelopment: "pre_deployment",
      highImpact: "high_impact",
      highImpactFactors: ["resource_allocation", "rights"],
      highImpactJustification:
        "The output determines which offeror wins an award, so it affects both the allocation of public resources and an offeror's ability to contest the outcome.",
      topicArea: "procurement_financial_management",
      aiClassification: "classical_predictive_ml",
      disseminatesToPublic: "no",
      scalable: "yes",
      hasATO: "no",
      systemSource: "in_house",
      trainingDataDescription: "Historical proposals and awarded ratings; no bias evaluation has been performed on the rating distribution.",
      hasPii: "no",
      demographicFeatures: ["none"],
      customCode: "yes",
      nationalSecuritySystem: "no",
      researchOnly: "no",
      independentReviewConducted: "in_progress",
      failSafeMechanism: "in_progress",
      feasibilitySummary:
        "Technically feasible, governance-blocked: no mandatory human evaluation, no appeal path, no bias evaluation on the rating distribution.",
      successMetrics: "Evaluation days per acquisition; rating variance between evaluators.",
      keyMetrics: ["time_saved", "quality_improvement"],
      timelineForResults: "6_12",
      metricsSummary: "Measured on evaluation days and rating variance — neither addresses the governance objection.",
      routeTo: ["governance"],
      reviewerNotes: "Decisional AI on award outcomes with human review answered 'no'. Blocked until the board evaluates independently and the tool is advisory.",
      readinessScore: "needs_work",
      readinessSummary: "Rejected as scoped. Resubmit as decision support with the board's own evaluation first and a disclosable rationale.",
      executiveSummary:
        "Technical evaluation is slow and varies by evaluator, so this would have a model issue the technical rating the board adopts as its evaluation of record. Rejected: it automates an award outcome with no mandatory human evaluation and no way for an offeror to contest how the ranking was produced. The efficiency goal is sound; the design is not.",
    } as Partial<FormData>),
  },

  // 3) AT&R / ACWS — in_review, partial governance so the reviewer checklist
  // has visible remaining work.
  {
    id: "es2-acws-closeout-completeness",
    submittedAt: hoursAgo(52),
    formData: mk({
      submitterName: "Dana Whitfield",
      submitterEmail: "dana.whitfield@es2.demo",
      submitterRole: "contract_specialist",
      submitterOffice: "atr",
      submitterSubOffice: "acws",
      reviewStatus: "in_review",
      useCaseTitle: "Contract File Completeness Check Before Closeout",
      useCaseDescription:
        "Checks a contract file against the closeout checklist and lists what is missing or unsigned, so the gap is found before the file reaches closeout rather than during an audit.",
      isWithheld: "no",
      targetAudience: "contract_specialist",
      impactedUsersCount: "50_500",
      painPoints:
        "Missing documentation is usually discovered at closeout or during an audit, long after the people who could explain it have moved on.",
      targetUserContext: "Contract specialists and closeout teams working files that may be several years old.",
      targetUserSummary: "Closeout teams reconstructing files after the fact.",
      coreProblem:
        "There is no early signal that a contract file is incomplete, so gaps surface at closeout when they are most expensive to fix.",
      problemImpact: "Late findings extend closeout, and unexplained gaps weaken the file under audit.",
      affectedBusinessUnits: ["contract_writing"],
      problemType: ["quality"],
      severity: "medium",
      problemDefinition: "Completeness is checked too late in the life of a contract file to be fixed cheaply.",
      proposedSolution:
        "A checker that compares each file against the closeout checklist, flags missing or unsigned items with a link to the requirement, and routes the list to the responsible specialist. It never marks a file complete on its own.",
      keyFunctionality: ["classification", "routing"],
      solutionSummary: "Checklist-based completeness flags routed to the responsible specialist.",
      deliveryAudience: "internal",
      userValue: "Specialists find the gap while the people who can close it are still on the file.",
      userTimeSavings: "1_5",
      otherUserImprovements: ["less_frustration", "more_consistent_work"],
      userValueSummary: "Earlier, cheaper fixes instead of closeout-time archaeology.",
      businessValue: "Shortens closeout and reduces audit findings tied to missing documentation.",
      costSavings: "50k_250k",
      strategicBenefit: ["operational_efficiency", "improve_quality"],
      businessValueSummary: "Fewer audit findings and a shorter closeout queue.",
      usptoFocusArea: ["atr_audit_readiness"],
      relevantOkrs: "Audit findings tied to file completeness; closeout cycle time.",
      alignmentSummary: "Direct fit with audit readiness and data quality.",
      implementationComplexity: "low",
      resourcesNeeded: ["content_owner", "infrastructure"],
      dependencies: "Machine-readable closeout checklist; access to file metadata across the contract writing system.",
      involvesSensitiveData: "no",
      securityClassification: "controlled",
      impactLevel: "cui",
      dataReadiness: "partial",
      accessControlRequirements: ["employee_authentication"],
      aiDecisionalImpact: "no",
      aiModelSourcing: "american_built",
      aiHumanReview: "yes",
      // Partial governance: stage and classification are in, but the
      // dissemination/scalability answers and ATO are still open.
      stageOfDevelopment: "pre_deployment",
      highImpact: "not_high_impact",
      topicArea: "procurement_financial_management",
      aiClassification: "classical_predictive_ml",
      feasibilitySummary: "Low complexity once the checklist is machine-readable. Governance record is still being completed.",
      successMetrics: "Audit findings tied to missing documentation; days in closeout.",
      keyMetrics: ["error_rate", "resolution_time"],
      timelineForResults: "3_6",
      routeTo: ["governance"],
      reviewerNotes: "Sensible and low-risk. Needs the dissemination and scalability answers plus an ATO position before sign-off.",
      readinessScore: "needs_work",
    } as Partial<FormData>),
  },

  // 4) AT&R / ACWS — approved. Speaks to the data-quality problem the program
  // just lived through during its migration.
  {
    id: "es2-acws-migration-data-quality",
    submittedAt: hoursAgo(110),
    formData: mk({
      submitterName: "Marcus Bell",
      submitterEmail: "marcus.bell@es2.demo",
      submitterRole: "analyst",
      submitterOffice: "atr",
      submitterSubOffice: "acws",
      reviewStatus: "approved",
      bureauSignoff: {
        bureau: "atr",
        decision: "approved",
        signedOffByName: "Alan Brooks",
        signedOffByEmail: "alan.brooks@es2.demo",
        signedOffAt: hoursAgo(78),
      },
      useCaseTitle: "Migration Data-Quality Triage Across Transferred Contract Files",
      useCaseDescription:
        "Ranks transferred contract files by how likely their data is wrong, so the cleanup team works the worst records first instead of sampling at random. Advisory: a person confirms every correction.",
      isWithheld: "no",
      targetAudience: "analyst",
      impactedUsersCount: "50_500",
      painPoints:
        "After a migration nobody knows which transferred records are trustworthy, and random sampling finds problems slowly while bad records keep being used.",
      targetUserContext: "Data-quality analysts working through records transferred from a retired system.",
      targetUserSummary: "Analysts triaging a large transferred record set with no priority order.",
      coreProblem:
        "Transferred records have uneven quality and no ranking, so cleanup effort is spread evenly instead of aimed at the records most likely to be wrong.",
      problemImpact: "Bad records stay in use longer and cleanup capacity is spent on records that were already fine.",
      affectedBusinessUnits: ["contract_writing", "it_systems"],
      problemType: ["quality", "productivity"],
      severity: "high",
      problemDefinition: "Cleanup after migration has no risk-based priority order.",
      proposedSolution:
        "A model that scores each transferred record for likely error using field-completeness, cross-field consistency, and mismatch against the system of record, then queues the highest-risk records for analyst confirmation.",
      keyFunctionality: ["classification", "ranking", "routing"],
      solutionSummary: "Risk-ranked cleanup queue with analyst confirmation on every correction.",
      deliveryAudience: "internal",
      userValue: "Analysts spend their time on the records most likely to be wrong.",
      userTimeSavings: "5_10",
      otherUserImprovements: ["better_decisions"],
      userValueSummary: "Cleanup effort aimed where the errors actually are.",
      businessValue: "Restores confidence in migrated data faster and shortens the period bad records stay in use.",
      costSavings: "250k_1m",
      strategicBenefit: ["operational_efficiency", "improve_quality"],
      businessValueSummary: "Faster return to trustworthy data after a migration.",
      usptoFocusArea: ["atr_audit_readiness", "atr_shared_data"],
      relevantOkrs: "Migrated-record error rate; time to a trustworthy baseline after cutover.",
      alignmentSummary: "Advances audit readiness and the standardized, shared data goal.",
      implementationComplexity: "medium",
      resourcesNeeded: ["ml_engineers", "infrastructure"],
      dependencies: "Access to both the transferred set and the system of record; an analyst confirmation queue.",
      involvesSensitiveData: "no",
      securityClassification: "controlled",
      impactLevel: "cui",
      dataReadiness: "ai_ready",
      trl: "7",
      accessControlRequirements: ["employee_authentication", "audit_logging"],
      aiDecisionalImpact: "no",
      aiModelSourcing: "american_built",
      aiHumanReview: "yes",
      stageOfDevelopment: "pilot",
      highImpact: "not_high_impact",
      topicArea: "information_technology",
      aiClassification: "classical_predictive_ml",
      disseminatesToPublic: "no",
      scalable: "yes",
      hasATO: "yes",
      atoSystemName: "Contract Writing System",
      systemSource: "in_house",
      operationalDate: "2026-05-15",
      trainingDataDescription: "Confirmed corrections from the first cleanup wave, used to rank the remainder.",
      hasPii: "no",
      demographicFeatures: ["none"],
      customCode: "yes",
      nationalSecuritySystem: "no",
      researchOnly: "no",
      feasibilitySummary: "Pilot running against the first cleanup wave. Advisory throughout, with confirmation on every correction.",
      successMetrics: "Error rate in the confirmed sample; records corrected per analyst week.",
      keyMetrics: ["error_rate", "productivity"],
      timelineForResults: "3_6",
      metricsSummary: "Compares error yield of the ranked queue against the random-sampling baseline.",
      routeTo: ["governance"],
      reviewerNotes: "Advisory, internal, no decisions about people. Approved for continued pilot.",
      readinessScore: "ready",
      readinessSummary: "Well-scoped and directly aimed at a problem the program has just lived through.",
    } as Partial<FormData>),
  },

  // 5) AT&R / ATIS — approved, not high-impact, everything else complete. This
  // is the seed's RMF `on_track` example (Measure/Manage are correctly
  // not_yet_applicable; Govern and Map are fully covered).
  {
    id: "es2-atis-course-content-refresh",
    submittedAt: hoursAgo(88),
    formData: mk({
      submitterName: "Priya Nair",
      submitterEmail: "priya.nair@es2.demo",
      submitterRole: "training_developer",
      submitterOffice: "atr",
      submitterSubOffice: "atis",
      reviewStatus: "approved",
      bureauSignoff: {
        bureau: "atr",
        decision: "approved",
        signedOffByName: "Alan Brooks",
        signedOffByEmail: "alan.brooks@es2.demo",
        signedOffAt: hoursAgo(64),
      },
      useCaseTitle: "Course Content Refresh When Doctrine Changes",
      useCaseDescription:
        "Watches published doctrine for changes and flags the course lessons that cite the changed passage, so a training developer knows what to revise instead of re-reading the catalog.",
      isWithheld: "no",
      targetAudience: "training_developer",
      impactedUsersCount: "gt_500",
      painPoints:
        "When doctrine changes, nobody knows which lessons went stale, so content stays out of date until someone happens to notice it in delivery.",
      targetUserContext: "Training developers maintaining a large course catalog across consolidated training systems.",
      targetUserSummary: "Developers responsible for keeping course content aligned to current doctrine.",
      coreProblem:
        "There is no link between a doctrine change and the lessons that depend on it, so stale content persists and is found by accident.",
      problemImpact: "Soldiers train against superseded content, and rework is discovered late and unevenly.",
      affectedBusinessUnits: ["training_management"],
      problemType: ["quality"],
      severity: "high",
      problemDefinition: "Course content has no traceable dependency on the doctrine it teaches.",
      proposedSolution:
        "A matcher that links lesson passages to the doctrine they cite, detects when the cited passage changes, and opens a revision task for the responsible developer with both versions shown side by side.",
      keyFunctionality: ["search", "classification", "routing"],
      solutionSummary: "Doctrine-change detection that opens targeted lesson revision tasks.",
      deliveryAudience: "internal",
      userValue: "Developers get a specific list of affected lessons instead of a catalog-wide review.",
      userTimeSavings: "5_10",
      otherUserImprovements: ["more_consistent_work", "better_decisions"],
      userValueSummary: "Targeted revision work instead of catalog-wide sweeps.",
      businessValue: "Keeps published training current and shortens the lag between a doctrine change and updated content.",
      costSavings: "250k_1m",
      strategicBenefit: ["improve_quality", "operational_efficiency"],
      businessValueSummary: "Shorter lag from doctrine change to current training content.",
      usptoFocusArea: ["atr_training_currency"],
      relevantOkrs: "Content currency against published doctrine; revision turnaround time.",
      alignmentSummary: "Squarely on the current, accessible training content priority.",
      implementationComplexity: "medium",
      resourcesNeeded: ["ml_engineers", "content_owner"],
      dependencies: "Versioned doctrine source with change events; lesson-to-citation mapping in the training catalog.",
      involvesSensitiveData: "no",
      securityClassification: "internal",
      impactLevel: "unclassified",
      dataReadiness: "ai_ready",
      trl: "7",
      accessControlRequirements: ["employee_authentication"],
      aiDecisionalImpact: "no",
      aiModelSourcing: "american_built",
      aiHumanReview: "yes",
      stageOfDevelopment: "pilot",
      highImpact: "not_high_impact",
      topicArea: "human_resources",
      aiClassification: "nlp",
      disseminatesToPublic: "no",
      scalable: "yes",
      hasATO: "no",
      systemSource: "in_house",
      operationalDate: "2026-04-01",
      trainingDataDescription: "Lesson text with existing doctrine citations; no personal data involved.",
      hasPii: "no",
      demographicFeatures: ["none"],
      customCode: "yes",
      nationalSecuritySystem: "no",
      researchOnly: "no",
      feasibilitySummary: "Pilot on one catalog area. Content-only, no personal data, and a developer confirms every revision task.",
      successMetrics: "Lag from doctrine change to revised lesson; share of affected lessons correctly identified.",
      keyMetrics: ["quality_improvement", "time_saved"],
      timelineForResults: "6_12",
      metricsSummary: "Measures detection coverage and revision lag against the current manual process.",
      routeTo: ["governance"],
      reviewerNotes: "Clean scope, no personal data, human confirms every task. Approved.",
      readinessScore: "ready",
      readinessSummary: "Complete governance record for a low-risk, high-value content-currency use case.",
    } as Partial<FormData>),
  },

  // 6) AT&R / ATIS — in_review with deliberately partial Map coverage, so the
  // RMF profile resolves to `partial` (attention), not `gap`.
  {
    id: "es2-atis-readiness-gap-prediction",
    submittedAt: hoursAgo(44),
    formData: mk({
      submitterName: "Priya Nair",
      submitterEmail: "priya.nair@es2.demo",
      submitterRole: "analyst",
      submitterOffice: "atr",
      submitterSubOffice: "atis",
      reviewStatus: "in_review",
      useCaseTitle: "Training Readiness Gap Prediction By Unit",
      useCaseDescription:
        "Projects which units are trending toward a training readiness shortfall in the next reporting period, so scheduling attention goes where the shortfall is forming rather than after it is reported.",
      isWithheld: "no",
      targetAudience: "supervisor",
      impactedUsersCount: "gt_500",
      painPoints:
        "Readiness shortfalls are visible only after the reporting period closes, which is too late to schedule the training that would have prevented them.",
      targetUserContext: "Training managers and supervisors planning seat allocation across units.",
      targetUserSummary: "Planners deciding where limited training seats should go next period.",
      coreProblem:
        "Readiness reporting is backward-looking, so planners react to a shortfall instead of preventing it.",
      problemImpact: "Seats are allocated late and units carry avoidable gaps into the next period.",
      affectedBusinessUnits: ["training_management"],
      problemType: ["productivity", "quality"],
      severity: "medium",
      problemDefinition: "Planners have no forward signal on where a training gap is forming.",
      proposedSolution:
        "A model over completion and expiry records that projects unit-level shortfall risk for the next period and surfaces it to planners alongside the underlying records. Unit-level only; it produces no output about an individual soldier.",
      keyFunctionality: ["classification", "ranking"],
      solutionSummary: "Forward-looking unit-level shortfall projection for seat planning.",
      deliveryAudience: "internal",
      userValue: "Planners see the forming gap while there is still time to schedule against it.",
      userTimeSavings: "1_5",
      otherUserImprovements: ["better_decisions"],
      userValueSummary: "Preventive seat planning instead of reactive catch-up.",
      businessValue: "Fewer carried-forward training gaps and better use of limited seats.",
      costSavings: "50k_250k",
      strategicBenefit: ["operational_efficiency"],
      businessValueSummary: "Better seat allocation and fewer carried gaps.",
      usptoFocusArea: ["atr_training_currency"],
      relevantOkrs: "Carried-forward training gaps; seat utilization.",
      alignmentSummary: "Supports training currency by making the gap visible before it is reported.",
      implementationComplexity: "medium",
      resourcesNeeded: ["ml_engineers", "infrastructure"],
      dependencies: "Completion and expiry history at unit level; agreement that output stays unit-level, never individual.",
      involvesSensitiveData: "yes",
      securityClassification: "controlled",
      impactLevel: "cui",
      dataReadiness: "partial",
      accessControlRequirements: ["employee_authentication", "pii_protection", "audit_logging"],
      aiDecisionalImpact: "no",
      aiModelSourcing: "american_built",
      aiHumanReview: "yes",
      // Partial Map coverage on purpose: stage, topic, classification and the
      // high-impact call are in; dissemination and scalability are not.
      stageOfDevelopment: "pre_deployment",
      highImpact: "not_high_impact",
      topicArea: "human_resources",
      aiClassification: "classical_predictive_ml",
      feasibilitySummary:
        "Depends on completion history quality and on holding the line that output stays unit-level. Governance record is still partial.",
      successMetrics: "Projection accuracy against realized shortfalls; seats reallocated on the projection.",
      keyMetrics: ["quality_improvement", "productivity"],
      timelineForResults: "6_12",
      routeTo: ["governance"],
      reviewerNotes:
        "Reasonable and unit-level by design. Needs the dissemination and scalability answers, and an explicit control that blocks individual-level output, before sign-off.",
      readinessScore: "needs_work",
    } as Partial<FormData>),
  },

  // 7) AT&R / ATIS — REJECTED. The second governance moment: decisional AI
  // about people's careers, drawn from training records, with no human review.
  {
    id: "es2-atis-promotion-screening",
    submittedAt: hoursAgo(130),
    formData: mk({
      submitterName: "Priya Nair",
      submitterEmail: "priya.nair@es2.demo",
      submitterRole: "program_manager",
      submitterOffice: "atr",
      submitterSubOffice: "atis",
      reviewStatus: "rejected",
      bureauSignoff: {
        bureau: "atr",
        decision: "rejected",
        signedOffByName: "Alan Brooks",
        signedOffByEmail: "alan.brooks@es2.demo",
        signedOffAt: hoursAgo(92),
      },
      comments: [
        {
          id: "c-atis-promotion-1",
          authorName: "Alan Brooks",
          authorRole: "reviewer",
          body: "Rejected as scoped. This screens individual soldiers for a career outcome from training records alone, with no mandatory human review and no route for the soldier to see or contest the basis. Training completion is a poor proxy for promotion potential, and the record set carries known coverage differences between units. Bring this back only as a data-quality aid for the board, never as a screen.",
          createdAt: hoursAgo(92),
        },
      ],
      useCaseTitle: "Automated Promotion Screening From Training Records",
      useCaseDescription:
        "Screens individual soldiers for promotion consideration by scoring their training record, producing a screened list the board works from directly.",
      isWithheld: "no",
      targetAudience: "supervisor",
      impactedUsersCount: "gt_500",
      painPoints:
        "Boards work through large candidate populations under time pressure, and preparing the record for each candidate is slow and uneven.",
      targetUserContext: "Promotion board members and the staff who assemble candidate records.",
      targetUserSummary: "Board members and staff preparing large candidate populations.",
      coreProblem:
        "Assembling and comparing candidate training records is slow, so board preparation consumes time that could go to deliberation.",
      problemImpact: "Preparation crowds out deliberation and record quality varies by the staff assembling it.",
      affectedBusinessUnits: ["training_management", "human_resources"],
      problemType: ["productivity"],
      severity: "high",
      problemDefinition: "Board preparation is manual and uneven across a large candidate population.",
      proposedSolution:
        "A model that scores each soldier's training record against historical promotion outcomes and returns a screened, ordered candidate list that the board works from as its starting population.",
      keyFunctionality: ["classification", "ranking"],
      solutionSummary: "Model-screened candidate list used as the board's starting population.",
      deliveryAudience: "internal",
      userValue: "Boards would spend less time assembling records.",
      userTimeSavings: "5_10",
      otherUserImprovements: ["more_consistent_work"],
      userValueSummary: "Faster preparation, at the cost of an unreviewed screen on a career outcome.",
      businessValue: "Would free board time, but the screen itself is the problem.",
      costSavings: "50k_250k",
      strategicBenefit: ["operational_efficiency"],
      businessValueSummary: "Preparation savings do not justify an unreviewed career screen.",
      usptoFocusArea: ["hrfm_force_decisions"],
      relevantOkrs: "Board preparation time; consistency of candidate records.",
      alignmentSummary: "Efficiency motive is legitimate; screening people for a career outcome without review is not.",
      implementationComplexity: "medium",
      resourcesNeeded: ["ml_engineers", "infrastructure"],
      dependencies: "Individual training histories and historical promotion outcomes; no review or contest path exists in the current design.",
      involvesSensitiveData: "yes",
      securityClassification: "controlled",
      impactLevel: "cui",
      dataReadiness: "partial",
      trl: "3",
      accessControlRequirements: ["employee_authentication", "pii_protection", "audit_logging"],
      aiDecisionalImpact: "yes",
      aiModelSourcing: "american_built",
      aiHumanReview: "no",
      stageOfDevelopment: "pre_deployment",
      highImpact: "high_impact",
      highImpactFactors: ["rights", "benefits_access"],
      highImpactJustification:
        "The output screens individual soldiers for a career outcome, affecting both their rights to a fair process and their access to advancement.",
      topicArea: "human_resources",
      aiClassification: "classical_predictive_ml",
      disseminatesToPublic: "no",
      scalable: "no",
      hasATO: "no",
      systemSource: "in_house",
      trainingDataDescription:
        "Individual training histories and historical promotion outcomes. Known coverage differences between units have not been evaluated for bias.",
      hasPii: "yes",
      demographicFeatures: ["none"],
      customCode: "yes",
      nationalSecuritySystem: "no",
      researchOnly: "no",
      independentReviewConducted: "in_progress",
      feasibilitySummary:
        "Governance-blocked: decisional about individuals, no mandatory human review, no contest path, and no bias evaluation against known record-coverage differences.",
      successMetrics: "Board preparation hours; agreement between screened list and board outcome.",
      keyMetrics: ["time_saved"],
      timelineForResults: "6_12",
      metricsSummary: "Neither proposed metric addresses fairness or contestability.",
      routeTo: ["governance"],
      reviewerNotes: "Decisional about people with human review answered 'no'. Not reconsiderable as a screen.",
      readinessScore: "early_stage",
      readinessSummary: "Rejected as scoped. A data-quality aid for the board is a different, acceptable idea.",
      executiveSummary:
        "Board preparation is slow, so this would score each soldier's training record and hand the board a screened candidate list. Rejected: it screens individuals for a career outcome with no mandatory human review, no route to contest the basis, and no bias evaluation against known coverage differences between units.",
    } as Partial<FormData>),
  },

  // 8) AT&R / FMS-ACES — needs_info. Drives the data-classification question:
  // partner-nation case material is where impact level actually bites.
  {
    id: "es2-fmsaces-case-translation",
    submittedAt: hoursAgo(36),
    formData: mk({
      submitterName: "Lena Okafor",
      submitterEmail: "lena.okafor@es2.demo",
      submitterRole: "analyst",
      submitterOffice: "atr",
      submitterSubOffice: "fmsaces",
      reviewStatus: "needs_info",
      comments: [
        {
          id: "c-fmsaces-translation-1",
          authorName: "Alan Brooks",
          authorRole: "reviewer",
          body: "Holding for information. Before this can move, we need the classification of the case material it would process and the required impact level of the hosting boundary, plus confirmation that nothing releasable to one partner can surface in another partner's session.",
          createdAt: hoursAgo(20),
        },
      ],
      useCaseTitle: "Case Document Translation For Partner Nations",
      useCaseDescription:
        "Produces working translations of security cooperation case material so case managers and partner-nation counterparts can work from the same text without waiting on a translation queue.",
      isWithheld: "no",
      targetAudience: "industry_partner",
      impactedUsersCount: "10_50",
      painPoints:
        "Case correspondence waits days in a translation queue, and case managers work from informal translations of uncertain quality in the meantime.",
      targetUserContext: "Case managers coordinating with partner-nation counterparts across languages.",
      targetUserSummary: "Case managers blocked on translation turnaround.",
      coreProblem:
        "Translation turnaround delays case execution, and the informal workaround has no quality or handling controls.",
      problemImpact: "Case milestones slip and unofficial translations circulate without review.",
      affectedBusinessUnits: ["security_cooperation"],
      problemType: ["productivity", "quality"],
      severity: "medium",
      problemDefinition: "Case execution is gated on a translation queue with no controlled interim option.",
      proposedSolution:
        "A translation service inside the accredited boundary that produces clearly-labelled working translations, keeps each case partitioned, and routes anything binding to official translation before release.",
      keyFunctionality: ["translation", "summarization"],
      solutionSummary: "Labelled working translations inside the boundary, with official translation for anything binding.",
      deliveryAudience: "external",
      userValue: "Case managers stop waiting days to understand incoming correspondence.",
      userTimeSavings: "1_5",
      otherUserImprovements: ["less_frustration"],
      userValueSummary: "Same-day working understanding of case correspondence.",
      businessValue: "Removes a recurring delay from case execution without loosening release controls.",
      costSavings: "50k_250k",
      strategicBenefit: ["operational_efficiency"],
      businessValueSummary: "Faster case execution with release control intact.",
      usptoFocusArea: ["atr_security_cooperation"],
      relevantOkrs: "Case milestone timeliness; quality and handling of case correspondence.",
      alignmentSummary: "Directly supports security cooperation case execution.",
      implementationComplexity: "medium",
      resourcesNeeded: ["ml_engineers", "infrastructure"],
      dependencies:
        "Classification determination for case material; an accredited hosting boundary at the required impact level; per-case partitioning so partner material cannot cross sessions.",
      involvesSensitiveData: "yes",
      securityClassification: "controlled",
      // Left blank on purpose — this is the open question the reviewer is
      // holding the submission for.
      impactLevel: "",
      dataReadiness: "needs_build",
      accessControlRequirements: ["employee_authentication", "audit_logging"],
      aiDecisionalImpact: "no",
      aiModelSourcing: "american_built",
      aiHumanReview: "yes",
      stageOfDevelopment: "pre_deployment",
      topicArea: "international_affairs",
      aiClassification: "generative_ai",
      feasibilitySummary:
        "Feasible only once classification and the required impact level are settled. Partitioning between partner cases is the hard requirement.",
      successMetrics: "Days from receipt to working understanding; official-translation volume avoided.",
      keyMetrics: ["time_saved", "resolution_time"],
      timelineForResults: "6_12",
      routeTo: ["governance"],
      reviewerNotes: "Held for classification and impact level. Partitioning between partner cases must be demonstrated, not asserted.",
      readinessScore: "needs_work",
    } as Partial<FormData>),
  },

  // 9) AT&R / FMS-ACES — submitted. Intake only: an idea, not yet vetted.
  {
    id: "es2-fmsaces-requisition-backlog",
    submittedAt: hoursAgo(14),
    formData: mk({
      submitterName: "Lena Okafor",
      submitterEmail: "lena.okafor@es2.demo",
      submitterRole: "analyst",
      submitterOffice: "atr",
      submitterSubOffice: "fmsaces",
      reviewStatus: "submitted",
      useCaseTitle: "Requisition Backlog Prioritization",
      useCaseDescription:
        "Orders the open requisition backlog by which items are most likely to hold up a case milestone, so case managers work the blocking items first.",
      isWithheld: "no",
      targetAudience: "analyst",
      impactedUsersCount: "50_500",
      painPoints:
        "The open backlog is worked roughly in date order, so an item blocking a milestone sits behind items that are not blocking anything.",
      targetUserContext: "Case managers and analysts working a large open requisition backlog.",
      targetUserSummary: "Case managers with no priority signal on a large backlog.",
      coreProblem:
        "The backlog has no priority order tied to case impact, so blocking items are not worked first.",
      problemImpact: "Case milestones slip on items that could have been cleared earlier.",
      affectedBusinessUnits: ["security_cooperation", "logistics_finance"],
      problemType: ["productivity"],
      severity: "medium",
      problemDefinition: "Backlog work order is not aligned to case impact.",
      proposedSolution:
        "A ranking over open requisitions using case milestone dependency, age, and historical clearance time, surfaced as a worklist a case manager can reorder.",
      keyFunctionality: ["ranking", "routing"],
      solutionSummary: "Impact-ordered requisition worklist that a case manager can override.",
      deliveryAudience: "internal",
      userValue: "Case managers see the blocking items first instead of inferring them.",
      userTimeSavings: "1_5",
      otherUserImprovements: ["better_decisions"],
      userValueSummary: "Blocking work surfaced first.",
      businessValue: "Fewer milestone slips attributable to backlog order.",
      costSavings: "50k_250k",
      strategicBenefit: ["operational_efficiency"],
      businessValueSummary: "Fewer avoidable milestone slips.",
      usptoFocusArea: ["atr_security_cooperation"],
      relevantOkrs: "Case milestone timeliness; backlog age.",
      alignmentSummary: "Supports case execution visibility.",
      implementationComplexity: "low",
      resourcesNeeded: ["infrastructure"],
      dependencies: "Milestone dependency data on requisitions; clearance history.",
      routeTo: ["governance"],
      readinessScore: "needs_work",
    } as Partial<FormData>),
  },

  // 10-12) THE CROSS-PROGRAM DUPLICATE GROUP — three program offices, one
  // idea. Written to share the vendor / past performance / award / risk /
  // score / delivery / history / protest / source selection vocabulary that
  // `similarity()` actually measures, while reading as three teams who each
  // arrived at it independently. Deliberately matches no consolidation
  // category — asserted in the test.
  //
  // 10) AT&R / Digital Market — submitted.
  {
    id: "es2-digitalmarket-vendor-past-performance",
    submittedAt: hoursAgo(30),
    formData: mk({
      submitterName: "Victor Hale",
      submitterEmail: "victor.hale@es2.demo",
      submitterRole: "product_owner",
      submitterOffice: "atr",
      submitterSubOffice: "digitalmarket",
      reviewStatus: "submitted",
      useCaseTitle: "Vendor Past-Performance Risk Scoring",
      useCaseDescription:
        "Gives a marketplace buyer an advisory past performance risk score on a vendor before an order is placed, with the delivery and quality history that produced the risk score shown alongside it.",
      isWithheld: "no",
      targetAudience: "contracting_officer",
      impactedUsersCount: "10_50",
      painPoints:
        "Past performance history for a vendor is scattered across records, so delivery risk is judged from whoever on the source selection team happens to remember a supplier.",
      targetUserContext: "Marketplace teams shaping an award and the source selection team that reviews vendor risk.",
      targetUserSummary: "Teams assessing vendor delivery risk before an award.",
      coreProblem:
        "Vendor past performance history is scattered across order records and never assembled, so a buyer judges delivery risk from whatever the source selection team happens to remember.",
      problemImpact: "Delivery risk surfaces after award, when the remedy is a protest or a termination rather than a different vendor.",
      affectedBusinessUnits: ["acquisition_marketplace", "contract_writing"],
      problemType: ["quality", "productivity"],
      severity: "high",
      problemDefinition: "There is no consolidated past performance risk signal on a vendor at the point of award.",
      proposedSolution:
        "A scoring service over the marketplace's own order history. It reads a vendor's delivery, quality, protest and termination history and returns an advisory past performance risk score, linked to the source records it used. The award decision stays with the contracting officer.",
      keyFunctionality: ["classification", "ranking", "search"],
      solutionSummary: "Advisory vendor past performance risk score, linked to the order records behind it.",
      deliveryAudience: "internal",
      userValue: "Teams see a vendor's delivery risk in one place instead of reconstructing it per award.",
      userTimeSavings: "1_5",
      otherUserImprovements: ["better_decisions"],
      userValueSummary: "One consolidated past performance risk view per vendor.",
      businessValue: "Fewer awards to suppliers with a known delivery history problem, and a recorded basis for the risk view.",
      costSavings: "50k_250k",
      strategicBenefit: ["operational_efficiency", "improve_quality"],
      businessValueSummary: "Better-informed awards and a defensible risk record.",
      usptoFocusArea: ["atr_acquisition_efficiency", "atr_shared_data"],
      relevantOkrs: "Award quality; time spent assembling a vendor risk view.",
      alignmentSummary: "Supports efficient acquisition and standardized, shared data.",
      implementationComplexity: "medium",
      resourcesNeeded: ["ml_engineers", "infrastructure"],
      dependencies: "Access to past performance records across systems; agreement on how protest and termination history is weighted.",
      routeTo: ["governance"],
      readinessScore: "needs_work",
    } as Partial<FormData>),
  },

  // 11) LOG-FIN — submitted. Same idea, arrived at from the supply side.
  {
    id: "es2-logfin-supplier-past-performance",
    submittedAt: hoursAgo(26),
    formData: mk({
      submitterName: "Sofia Marquez",
      submitterEmail: "sofia.marquez@es2.demo",
      submitterRole: "contracting_officer",
      submitterOffice: "logfin",
      reviewStatus: "submitted",
      useCaseTitle: "Vendor Past-Performance Risk Scoring For Supply Awards",
      useCaseDescription:
        "Assembles a supplier's delivery and quality history into one advisory past performance risk score ahead of a supply award, so the source selection team sees the risk while the award can still change.",
      isWithheld: "no",
      targetAudience: "contracting_officer",
      impactedUsersCount: "10_50",
      painPoints:
        "A supplier's delivery history lives in records nobody assembles before an award, so past performance risk is carried in the heads of a few people on the source selection team.",
      targetUserContext: "Contracting officers and analysts making supply awards against recurring requirements.",
      targetUserSummary: "Officers judging supplier delivery risk before a supply award.",
      coreProblem:
        "Nobody assembles a supplier's past performance ahead of a recurring supply award, so delivery risk lives in the memory of a few analysts and a weak performer wins again.",
      problemImpact: "A supplier with a poor delivery history wins again, and the shortfall shows up as a sustainment problem months later.",
      affectedBusinessUnits: ["logistics_finance", "contract_writing"],
      problemType: ["quality"],
      severity: "high",
      problemDefinition: "Supply awards are made without a consolidated past performance risk signal on the supplier.",
      proposedSolution:
        "A model over requisition and receipt records. It reads a supplier's delivery, quality, protest and termination history and publishes an advisory past performance risk score, linked to the source records, to the source selection team. A contracting officer still makes the award.",
      keyFunctionality: ["classification", "ranking"],
      solutionSummary: "Advisory supplier past performance risk rating for supply awards, drawn from requisition and receipt records.",
      deliveryAudience: "internal",
      userValue: "Officers see a supplier's delivery history assembled rather than remembered.",
      userTimeSavings: "1_5",
      otherUserImprovements: ["better_decisions"],
      userValueSummary: "Assembled past performance history instead of institutional memory.",
      businessValue: "Fewer repeat awards to suppliers with a known delivery risk, and fewer sustainment surprises.",
      costSavings: "50k_250k",
      strategicBenefit: ["operational_efficiency", "improve_quality"],
      businessValueSummary: "Better supply awards and fewer downstream sustainment problems.",
      usptoFocusArea: ["logfin_supply_visibility", "logfin_audit_sustainment"],
      relevantOkrs: "Supply award quality; sustainment shortfalls traced to supplier delivery.",
      alignmentSummary: "Supports sustainment and supply visibility.",
      implementationComplexity: "medium",
      resourcesNeeded: ["ml_engineers", "infrastructure"],
      dependencies: "Past performance and delivery records for recurring suppliers; agreement on scoring weights.",
      routeTo: ["governance"],
      readinessScore: "needs_work",
    } as Partial<FormData>),
  },

  // 12) BTS — submitted. Same idea again, framed as a shared enterprise
  // service rather than a program feature.
  {
    id: "es2-bts-supplier-risk-scoring",
    submittedAt: hoursAgo(22),
    formData: mk({
      submitterName: "Andre Duval",
      submitterEmail: "andre.duval@es2.demo",
      submitterRole: "developer",
      submitterOffice: "bts",
      reviewStatus: "submitted",
      useCaseTitle: "Supplier Past-Performance Risk Scoring Before Award",
      useCaseDescription:
        "One shared service any program can call for an advisory past performance risk score on a supplier or vendor before an award, instead of each source selection team building its own delivery risk view.",
      isWithheld: "no",
      targetAudience: "program_manager",
      impactedUsersCount: "50_500",
      painPoints:
        "Several programs are each assembling their own view of vendor past performance history, so the same delivery risk question is answered differently depending on which source selection team asks it.",
      targetUserContext: "Program teams that need a vendor risk view but have no system of record for past performance.",
      targetUserSummary: "Programs each rebuilding the same supplier risk view.",
      coreProblem:
        "Several programs each assemble their own vendor past performance history, so the same supplier gets a different delivery risk answer depending on which source selection team asks.",
      problemImpact: "Duplicate effort across programs, and the same vendor gets a different risk answer depending on who asks.",
      affectedBusinessUnits: ["it_systems", "cross_functional"],
      problemType: ["quality", "productivity"],
      severity: "medium",
      problemDefinition: "There is no shared past performance risk service, so each program builds its own.",
      proposedSolution:
        "A single scoring service exposed to every program. It reads a supplier's delivery, quality, protest and termination history from the records each program already holds and returns an advisory past performance risk score, linked to the source records. Each program keeps its award decision with its own contracting officer.",
      keyFunctionality: ["classification", "ranking", "search"],
      solutionSummary: "Shared advisory past performance risk score for any program making an award.",
      deliveryAudience: "internal",
      userValue: "Programs get a consistent vendor delivery risk view without building one each.",
      userTimeSavings: "1_5",
      otherUserImprovements: ["more_consistent_work", "better_decisions"],
      userValueSummary: "One consistent risk answer instead of several.",
      businessValue: "Removes duplicate builds and makes the past performance risk view consistent across awards.",
      costSavings: "250k_1m",
      strategicBenefit: ["operational_efficiency", "improve_quality"],
      businessValueSummary: "One shared service instead of several partial ones.",
      usptoFocusArea: ["bts_reduce_duplication", "bts_modernization"],
      relevantOkrs: "Duplicate application count; consistency of supplier risk answers across programs.",
      alignmentSummary: "Squarely on reducing duplicate systems.",
      implementationComplexity: "medium",
      resourcesNeeded: ["ml_engineers", "infrastructure"],
      dependencies: "A shared past performance record source; per-program access rules; agreement on common scoring weights.",
      routeTo: ["governance"],
      readinessScore: "needs_work",
    } as Partial<FormData>),
  },

  // 13-14) THE CONSOLIDATION GROUP — both match lib/ombConsolidation.ts's
  // "meeting_transcription" category, so they collapse into one inventory row
  // AND are correctly excluded from duplicate detection.
  //
  // 13) HR-FM — submitted.
  {
    id: "es2-hrfm-meeting-transcription",
    submittedAt: hoursAgo(18),
    formData: mk({
      submitterName: "Renee Calder",
      submitterEmail: "renee.calder@es2.demo",
      submitterRole: "it_staff",
      submitterOffice: "hrfm",
      reviewStatus: "submitted",
      useCaseTitle: "Meeting Transcription And Action Items",
      useCaseDescription:
        "Commercial meeting transcription that produces a transcript and a draft action-item list for staff sessions, which the chair edits before it is circulated.",
      isWithheld: "no",
      targetAudience: "analyst",
      impactedUsersCount: "50_500",
      painPoints: "Notes are taken by hand and by whoever is least busy, so action items are missed or land without an owner.",
      targetUserContext: "Staff running recurring personnel and force-management working sessions.",
      targetUserSummary: "Staff who currently take notes by hand in recurring sessions.",
      coreProblem: "Action items from working sessions are captured inconsistently and sometimes not at all.",
      problemImpact: "Follow-through depends on who took notes, and commitments get lost between sessions.",
      affectedBusinessUnits: ["human_resources"],
      problemType: ["productivity"],
      severity: "low",
      problemDefinition: "Working-session notes and action items are inconsistently captured.",
      proposedSolution:
        "Enable the commercial meeting transcription capability already in the collaboration suite, with the chair reviewing and editing the action-item list before circulation.",
      keyFunctionality: ["summarization"],
      solutionSummary: "Commercial meeting transcription with a chair-reviewed action-item list.",
      deliveryAudience: "internal",
      userValue: "Staff stop hand-taking notes and get a consistent action-item list.",
      userTimeSavings: "lt_1",
      otherUserImprovements: ["less_frustration"],
      userValueSummary: "Consistent notes without a designated note-taker.",
      businessValue: "Better follow-through on commitments made in working sessions.",
      costSavings: "lt_50k",
      strategicBenefit: ["employee_experience"],
      businessValueSummary: "Modest, broad productivity gain.",
      usptoFocusArea: ["hrfm_self_service"],
      relevantOkrs: "Follow-through on working-session commitments.",
      alignmentSummary: "Low-risk enablement of an existing commercial capability.",
      implementationComplexity: "low",
      resourcesNeeded: ["infrastructure"],
      dependencies: "Collaboration suite licensing; a handling rule for sessions that touch personnel matters.",
      routeTo: ["governance"],
      readinessScore: "needs_work",
    } as Partial<FormData>),
  },

  // 14) LOG-FIN — submitted. Same commercial capability, different office —
  // which is exactly what the consolidated reporting lane exists for.
  {
    id: "es2-logfin-meeting-transcription",
    submittedAt: hoursAgo(16),
    formData: mk({
      submitterName: "Sofia Marquez",
      submitterEmail: "sofia.marquez@es2.demo",
      submitterRole: "program_manager",
      submitterOffice: "logfin",
      reviewStatus: "submitted",
      useCaseTitle: "Meeting Transcription For Program Reviews",
      useCaseDescription:
        "Commercial meeting transcription for program review sessions, producing a transcript and a decision log the program manager confirms before it is filed.",
      isWithheld: "no",
      targetAudience: "program_manager",
      impactedUsersCount: "10_50",
      painPoints: "Decisions made in program reviews are reconstructed afterwards from partial notes, and the record varies by reviewer.",
      targetUserContext: "Program managers and staff running recurring program review sessions.",
      targetUserSummary: "Program staff reconstructing decisions from partial notes.",
      coreProblem: "There is no reliable record of what was decided in a program review.",
      problemImpact: "Decisions get relitigated and the audit trail for a program decision is thin.",
      affectedBusinessUnits: ["logistics_finance"],
      problemType: ["productivity", "quality"],
      severity: "low",
      problemDefinition: "Program review decisions lack a consistent contemporaneous record.",
      proposedSolution:
        "Enable the commercial meeting transcription capability for program reviews, with the program manager confirming the decision log before it is filed to the program record.",
      keyFunctionality: ["summarization"],
      solutionSummary: "Commercial meeting transcription with a confirmed decision log filed to the program record.",
      deliveryAudience: "internal",
      userValue: "Program staff stop reconstructing decisions from partial notes.",
      userTimeSavings: "lt_1",
      otherUserImprovements: ["more_consistent_work"],
      userValueSummary: "A contemporaneous, confirmed decision record.",
      businessValue: "A defensible record of program decisions with almost no new build.",
      costSavings: "lt_50k",
      strategicBenefit: ["operational_efficiency"],
      businessValueSummary: "Cheap, defensible program decision record.",
      usptoFocusArea: ["logfin_audit_sustainment"],
      relevantOkrs: "Completeness of the program decision record.",
      alignmentSummary: "Supports audit sustainment at very low cost.",
      implementationComplexity: "low",
      resourcesNeeded: ["infrastructure"],
      dependencies: "Collaboration suite licensing; a filing rule for the confirmed decision log.",
      routeTo: ["governance"],
      readinessScore: "needs_work",
    } as Partial<FormData>),
  },

  // 15) AT&R, no program — DRAFT, so "resume your draft" has content on the
  // submitter's own dashboard. Intake fields only, and deliberately unfinished.
  {
    id: "es2-atr-schedule-risk-draft",
    submittedAt: hoursAgo(5),
    formData: mk({
      submitterName: "Victor Hale",
      submitterEmail: "victor.hale@es2.demo",
      submitterRole: "product_owner",
      submitterOffice: "atr",
      reviewStatus: "draft",
      useCaseTitle: "Schedule Risk Prediction From The Integrated Master Schedule",
      useCaseDescription:
        "Flags the schedule branches most likely to slip next quarter, using the integrated master schedule and how similar branches behaved before.",
      isWithheld: "",
      targetAudience: "program_manager",
      impactedUsersCount: "10_50",
      painPoints: "Slips are reported after they happen, so the first warning arrives when the date has already moved.",
      targetUserContext: "Program managers reviewing the integrated master schedule each cycle.",
      coreProblem: "There is no forward signal on which schedule branches are about to slip.",
      problemImpact: "Recovery starts after the slip instead of before it.",
      affectedBusinessUnits: ["cross_functional"],
      problemType: ["productivity"],
      severity: "medium",
      proposedSolution:
        "Compare the current integrated master schedule against how similar branches behaved historically and surface the branches trending toward a slip.",
      routeTo: ["draft"],
    } as Partial<FormData>),
  },
]
