// Department of Commerce demo seed — the deterministic "golden state" the
// admin Demo Data reset restores. Used when NEXT_PUBLIC_TENANT=doc. Mirrors
// the shape of lib/seedSubmissions.ts but spans Commerce bureaus (NIST,
// Census, ITA, NOAA, USPTO, BIS, OS, MBDA) with every review status
// represented (including a draft and a rejected idea), a few intentional
// near-duplicates across bureaus to demonstrate the cross-bureau
// rationalization / duplicate-detection story and double as a Decision
// Center comparison pair, OMB reportability variety (reportable / excluded /
// needs-review), and a high-impact example with its risk fields populated.
//
// Every id and owner email below is deterministic on purpose: the admin
// "Reset Demo Data" button wipes and re-inserts this exact array, so a
// submitter logged in with one of these emails sees the same "My ideas" list
// every time. See app/api/seed/route.ts for the reset/idempotency mechanics.
//
// submitterOffice values are bureau codes from lib/tenant/doc.ts; labels render
// via getTenant().unit.options. usptoFocusArea holds DoC focus-area ids.
// submitterSubOffice, where set, is an office code under that bureau's
// `offices` (Census, ITA, NOAA) — demonstrates the office roll-up drill-down.

import type { FormData } from "@/lib/steps"
import { initialFormData } from "@/lib/steps"
import { type Submission } from "@/lib/submissions"

function mk(partial: Partial<FormData>): FormData {
  return { ...initialFormData, ...partial }
}

const hoursAgo = (h: number) => new Date(Date.now() - 1000 * 60 * 60 * h).toISOString()

export const docSeedSubmissions: Submission[] = [
  // 1) CENSUS — public-facing plain-language assistant. [near-duplicate A]
  {
    id: "doc-census-survey-assistant",
    submittedAt: hoursAgo(3),
    formData: mk({
      submitterName: "Dana Whitfield",
      submitterEmail: "dana.whitfield@census.gov",
      submitterRole: "product_owner",
      submitterOffice: "census",
      submitterSubOffice: "demographic",
      reviewStatus: "in_review",
      useCaseTitle: "Plain-Language Survey Help Assistant",
      useCaseDescription:
        "A public-facing assistant that answers respondents' questions about Census surveys in plain language, citing official guidance, in multiple languages, and hands off to a person for anything sensitive. Informational only.",
      publicIndicator: "public",
      targetAudience: "applicant",
      impactedUsersCount: "gt_500",
      painPoints:
        "Respondents drop out or call for help when survey questions or instructions are confusing; limited-English respondents are underserved and call volume spikes during collection periods.",
      targetUserContext: "Members of the public completing Census surveys, plus the contact-center staff who field their questions.",
      targetUserSummary: "Survey respondents (especially first-time and limited-English) and the contact-center staff supporting them.",
      coreProblem:
        "Respondents can't get fast, plain-language help with survey questions, lowering completion rates and driving avoidable call volume.",
      problemImpact: "Confusion lowers response rates and raises contact-center load during collection windows.",
      affectedSystem: "cross_functional",
      problemType: ["user_experience", "productivity"],
      severity: "high",
      problemDefinition:
        "Survey respondents lack fast, accessible, plain-language help, lowering completion and increasing contact-center load.",
      proposedSolution:
        "A retrieval-grounded assistant that answers only from official survey guidance with a citation per answer, rewrites in plain language across languages, and hands off to a person for anything sensitive. Informational only; it never collects or decides survey responses.",
      keyFunctionality: ["question_answering", "search", "summarization", "translation"],
      solutionSummary: "Source-grounded, multilingual, plain-language survey help with citations and human handoff. Informational only.",
      userValue: "Respondents get clear answers in seconds, in their language, and can finish the survey without calling.",
      userTimeSavings: "1_5",
      otherUserImprovements: ["less_frustration", "better_decisions"],
      userValueSummary: "Instant, plain-language, multilingual survey help; higher completion.",
      businessValue: "Raises survey completion and deflects contact-center volume; improves accessibility and public trust.",
      costSavings: "250k_1m",
      strategicBenefit: ["operational_efficiency", "employee_experience"],
      businessValueSummary: "Higher completion + meaningful contact deflection, with a more accessible respondent experience.",
      usptoFocusArea: ["customer_experience", "omb_public_trust", "omb_governance"],
      relevantOkrs: "Survey response rate and accessibility; plain-language and Section 508 commitments; responsible-AI use.",
      alignmentSummary: "Advances customer experience and public trust under a responsible-AI design (source-grounded, cited, human handoff).",
      implementationComplexity: "medium",
      resourcesNeeded: ["ml_engineers", "content_owner", "infrastructure"],
      dependencies: "Authoritative survey-guidance corpus; multilingual + Section 508 review; scoped no-PII design (no response collection).",
      involvesSensitiveData: "no",
      securityClassification: "internal",
      accessControlRequirements: ["audit_logging"],
      aiDecisionalImpact: "no",
      aiModelSourcing: "american_built",
      aiHumanReview: "yes",
      stageOfDevelopment: "pilot",
      highImpact: "no",
      hasATO: "in_progress",
      systemSource: "contract",
      feasibilitySummary:
        "Medium complexity; public-facing so the bar is answer groundedness, 508 conformance, and multilingual accuracy, validated in a pilot. American-built, informational only with human handoff.",
      successMetrics: "Survey completion rate, deflection rate, human-rated answer groundedness, CSAT, language coverage — vs a control.",
      keyMetrics: ["user_satisfaction", "ticket_volume_reduction", "adoption_rate"],
      timelineForResults: "6_12",
      metricsSummary: "Pilot measures completion, deflection, groundedness, and CSAT against a control.",
      routeTo: ["governance"],
      reviewerNotes: "High-impact public-facing CX play; validate groundedness + 508 before public exposure.",
      readinessScore: "ready",
      readinessSummary: "Comprehensive, customer-centered, responsible-AI by design. Fund with a pilot condition: validate groundedness, 508, and multilingual accuracy before public exposure.",
      executiveSummary:
        "Census respondents can't get fast, plain-language help, lowering completion and driving call volume. This public-facing, source-grounded, multilingual assistant answers from official guidance with citations and hands off to a person, never collecting or deciding responses. Expected: higher completion and meaningful contact deflection. American-built, informational only. Fund with a pilot condition on groundedness and 508.",
    } as Partial<FormData>),
  },

  // 2) ITA — public-facing exporter assistant. [near-duplicate A — same pattern as Census]
  {
    id: "doc-ita-exporter-assistant",
    submittedAt: hoursAgo(7),
    formData: mk({
      submitterName: "Marcus Bell",
      submitterEmail: "marcus.bell@trade.gov",
      submitterRole: "product_owner",
      submitterOffice: "ita",
      submitterSubOffice: "global_markets",
      reviewStatus: "submitted",
      useCaseTitle: "Exporter Assistance Plain-Language Assistant",
      useCaseDescription:
        "A public-facing assistant that helps U.S. businesses navigate export programs and answers common trade questions in plain language, citing official ITA resources, with handoff to a trade specialist.",
      publicIndicator: "public",
      targetAudience: "applicant",
      impactedUsersCount: "gt_500",
      painPoints:
        "Small exporters struggle to navigate trade programs and get plain answers; specialists field the same routine questions repeatedly.",
      targetUserContext: "U.S. businesses (especially small exporters) using ITA services, plus the trade specialists who support them.",
      targetUserSummary: "Small and first-time exporters, plus the ITA trade specialists who support them.",
      coreProblem: "Exporters can't get fast, plain-language answers about trade programs, slowing them down and loading specialists with routine questions.",
      problemImpact: "Routine questions dominate specialist time and slow exporters who don't know where to start.",
      affectedSystem: "cross_functional",
      problemType: ["user_experience", "productivity"],
      severity: "medium",
      problemDefinition: "Exporters lack fast, plain-language guidance on trade programs, slowing them and loading specialists.",
      proposedSolution:
        "A retrieval-grounded assistant answering only from official ITA content with citations, in plain language, with handoff to a trade specialist for complex or sensitive cases. Informational only.",
      keyFunctionality: ["question_answering", "search", "summarization"],
      solutionSummary: "Source-grounded, plain-language exporter assistant with citations and specialist handoff. Informational only.",
      userValue: "Exporters get clear, correct answers fast and know their next step, without waiting on a specialist.",
      userTimeSavings: "1_5",
      otherUserImprovements: ["less_frustration", "better_decisions"],
      userValueSummary: "Fast, plain-language export guidance with a specialist one click away.",
      businessValue: "Deflects routine exporter questions, frees specialists for high-value engagements, and improves the exporter experience.",
      costSavings: "50k_250k",
      strategicBenefit: ["operational_efficiency", "employee_experience"],
      businessValueSummary: "Specialist time reclaimed and a faster, clearer exporter experience.",
      usptoFocusArea: ["customer_experience", "omb_public_trust"],
      relevantOkrs: "Exporter support responsiveness; plain-language and accessibility; responsible-AI use.",
      alignmentSummary: "Customer experience for exporters under a responsible-AI, informational-only design.",
      implementationComplexity: "medium",
      resourcesNeeded: ["ml_engineers", "content_owner"],
      dependencies: "Authoritative ITA content corpus; plain-language + 508 review.",
      involvesSensitiveData: "no",
      securityClassification: "internal",
      accessControlRequirements: ["audit_logging"],
      aiDecisionalImpact: "no",
      aiModelSourcing: "american_built",
      aiHumanReview: "yes",
      stageOfDevelopment: "pre_deployment",
      highImpact: "no",
      hasATO: "no",
      systemSource: "contract",
      feasibilitySummary: "Medium complexity; public-facing, so groundedness and 508 are the bar. American-built, informational only with specialist handoff.",
      successMetrics: "Deflection rate, exporter satisfaction, answer groundedness, time-to-answer — vs a control.",
      keyMetrics: ["ticket_volume_reduction", "user_satisfaction", "resolution_time"],
      timelineForResults: "6_12",
      metricsSummary: "Pilot tracks deflection, satisfaction, and groundedness against a control.",
      routeTo: ["governance"],
      reviewerNotes: "Strong CX case; near-identical pattern to the Census survey assistant — candidate for shared build (rationalization).",
      readinessScore: "ready",
      readinessSummary: "Solid, low-risk public-facing CX case; validate groundedness and 508 in a pilot. Note the strong overlap with the Census assistant.",
      executiveSummary:
        "Small exporters can't get fast, plain-language help navigating ITA trade programs, loading specialists with routine questions. This source-grounded, plain-language assistant answers from official ITA content with citations and hands off to a specialist. Expected: specialist time reclaimed and a faster exporter experience. American-built, informational only. Note: this is nearly the same pattern as Census's survey assistant — a strong candidate to build once and share.",
    } as Partial<FormData>),
  },

  // 3) OS / cross-cutting — agent-assist copilot. Lower-risk alternative to the public assistants. [near-duplicate A — workflow sibling]
  {
    id: "doc-os-response-copilot",
    submittedAt: hoursAgo(10),
    formData: mk({
      submitterName: "Renee Caldwell",
      submitterEmail: "renee.caldwell@doc.gov",
      submitterRole: "manager",
      submitterOffice: "os",
      reviewStatus: "submitted",
      useCaseTitle: "Customer-Service Response Copilot (Agent Assist)",
      useCaseDescription:
        "An internal copilot that drafts suggested replies for Commerce contact-center representatives to review, edit, and send, pulling from approved knowledge with citations. Never auto-sends; not public-facing.",
      publicIndicator: "public",
      targetAudience: "other",
      impactedUsersCount: "50_500",
      painPoints: "Representatives across bureaus draft the same routine answers by hand; quality varies and SLAs slip at peak.",
      targetUserContext: "Contact-center representatives across Commerce bureaus and their supervisors.",
      targetUserSummary: "Commerce contact-center representatives; indirect benefit to the public awaiting replies.",
      coreProblem: "Representatives spend most of their time drafting repetitive responses by hand, with inconsistent quality, slowing responses.",
      problemImpact: "Routine drafting consumes representative time; inconsistency drives rework and re-contacts.",
      affectedSystem: "cross_functional",
      problemType: ["productivity", "user_experience"],
      severity: "medium",
      problemDefinition: "Representatives lack a fast, consistent way to draft accurate replies, slowing responses and producing uneven quality.",
      proposedSolution:
        "A copilot that retrieves the right answer from an approved knowledge base and drafts a suggested, cited reply. The representative edits and approves every message; the assistant never sends. Low-confidence drafts flagged; all logged.",
      keyFunctionality: ["question_answering", "summarization", "search"],
      solutionSummary: "Agent-console copilot drafting cited replies from approved knowledge; rep approves every send. Internal only; fully logged.",
      userValue: "Representatives answer faster and more consistently and ramp quicker, with less repetitive drafting.",
      userTimeSavings: "5_10",
      otherUserImprovements: ["more_consistent_work", "less_frustration"],
      userValueSummary: "Faster, more consistent responses; the rep stays author and approver.",
      businessValue: "Higher throughput and consistency without putting AI in front of the public — a low-risk first step.",
      costSavings: "250k_1m",
      strategicBenefit: ["operational_efficiency", "employee_experience"],
      businessValueSummary: "Higher throughput and consistency with a low-risk, human-approved posture.",
      usptoFocusArea: ["customer_experience", "omb_governance"],
      relevantOkrs: "Response-time and quality targets; responsible-AI use with mandatory human review.",
      alignmentSummary: "Improves customer experience indirectly through staff, under a low-risk, human-approved design.",
      implementationComplexity: "low",
      resourcesNeeded: ["ml_engineers", "content_owner"],
      dependencies: "Approved knowledge base; agent-console integration; a measured baseline already available.",
      involvesSensitiveData: "no",
      securityClassification: "internal",
      accessControlRequirements: ["employee_authentication", "audit_logging"],
      aiDecisionalImpact: "no",
      aiModelSourcing: "american_built",
      aiHumanReview: "yes",
      stageOfDevelopment: "pilot",
      highImpact: "no",
      hasATO: "no",
      systemSource: "in_house",
      feasibilitySummary: "Low complexity and low risk: internal only, human-approved on every send, fully logged, American-built, with a measured pilot baseline.",
      successMetrics: "Handle time, first-contact resolution, consistency pass rate, draft-adoption rate — vs a baseline.",
      keyMetrics: ["resolution_time", "productivity", "user_satisfaction"],
      timelineForResults: "3_6",
      metricsSummary: "Tracks handle time, first-contact resolution, and consistency against a baseline.",
      routeTo: ["governance"],
      reviewerNotes: "Clean, low-risk, measured. Strong candidate to fund first as the lower-risk path to the public-assistant goal.",
      readinessScore: "ready",
      readinessSummary: "Low-risk, well-scoped, measurable; internal only, human-approved, logged, American-built. Ready to fund.",
      executiveSummary:
        "Commerce representatives draft routine replies by hand, with quality varying and SLAs slipping. This internal copilot drafts a cited reply from approved knowledge for the rep to edit and approve — never sending on its own. Expected: faster, more consistent responses. Low complexity, low risk, American-built, with a measured baseline. A strong lower-risk first step toward the public-facing assistants.",
    } as Partial<FormData>),
  },

  // 4) NIST — internal knowledge assistant. Approved (a completed example).
  {
    id: "doc-nist-standards-assistant",
    submittedAt: hoursAgo(40),
    formData: mk({
      submitterName: "Priya Nair",
      submitterEmail: "priya.nair@nist.gov",
      submitterRole: "it_staff",
      submitterOffice: "nist",
      reviewStatus: "approved",
      useCaseTitle: "Standards & Publications Knowledge Assistant",
      useCaseDescription:
        "An internal cited-source assistant that helps NIST staff find and summarize relevant standards, publications, and internal guidance, with links to the source documents.",
      publicIndicator: "public",
      targetAudience: "other",
      impactedUsersCount: "50_500",
      painPoints: "Staff spend significant time locating the right standard or publication across a large, fragmented corpus.",
      targetUserContext: "NIST technical and program staff who reference standards and publications daily.",
      targetUserSummary: "NIST staff who need to find and cite the right standards and publications quickly.",
      coreProblem: "Finding the right standard or publication is slow and inconsistent across a large corpus.",
      problemImpact: "Search time is a recurring tax on technical staff and leads to missed or outdated references.",
      affectedSystem: "cross_functional",
      problemType: ["productivity"],
      severity: "medium",
      problemDefinition: "NIST staff lack a fast, cited way to retrieve and summarize relevant standards and publications.",
      proposedSolution:
        "A retrieval assistant over the standards/publications corpus that returns ranked, cited results with short summaries and links. Informational only; staff verify and decide.",
      keyFunctionality: ["search", "summarization", "question_answering"],
      solutionSummary: "Cited retrieval + summarization over standards and publications. Informational only.",
      userValue: "Staff find the right cited source in seconds instead of hunting across systems.",
      userTimeSavings: "1_5",
      otherUserImprovements: ["better_decisions", "more_consistent_work"],
      userValueSummary: "Fast, cited retrieval of standards and publications.",
      businessValue: "Reclaims staff time and improves citation consistency and currency.",
      costSavings: "50k_250k",
      strategicBenefit: ["operational_efficiency"],
      businessValueSummary: "Reclaimed staff time and more consistent, current citations.",
      usptoFocusArea: ["omb_innovation", "customer_experience"],
      relevantOkrs: "Staff productivity; knowledge accessibility; responsible-AI use.",
      alignmentSummary: "Internal productivity with a low-risk, cited, informational design.",
      implementationComplexity: "low",
      resourcesNeeded: ["ml_engineers", "content_owner"],
      dependencies: "Access to the standards/publications corpus and search index.",
      involvesSensitiveData: "no",
      securityClassification: "internal",
      accessControlRequirements: ["employee_authentication", "audit_logging"],
      aiDecisionalImpact: "no",
      aiModelSourcing: "open_source_us",
      aiHumanReview: "yes",
      stageOfDevelopment: "deployed",
      highImpact: "no",
      hasATO: "yes",
      systemSource: "in_house",
      feasibilitySummary: "Low complexity, low risk: internal, cited, informational only, U.S.-hosted open-source model.",
      successMetrics: "Search time, answer-acceptance rate, citation accuracy — vs a baseline.",
      keyMetrics: ["time_saved", "user_satisfaction", "quality_improvement"],
      timelineForResults: "3_6",
      metricsSummary: "Tracks search time and citation accuracy against a baseline.",
      routeTo: ["governance"],
      reviewerNotes: "Approved: low-risk internal productivity tool with a clean responsible-AI posture.",
      readinessScore: "ready",
      readinessSummary: "Low-risk, measurable, cited, informational only. Approved for implementation.",
      executiveSummary:
        "NIST staff spend significant time locating the right standard or publication across a large corpus. This internal assistant returns ranked, cited results with summaries and links; staff verify and decide. Expected: reclaimed staff time and more consistent citations. Low risk, U.S.-hosted open-source model, informational only. Approved.",
    } as Partial<FormData>),
  },

  // 5) USPTO — examiner assist. In review; strong Decision Center candidate.
  {
    id: "doc-uspto-conflict-search",
    submittedAt: hoursAgo(26),
    formData: mk({
      submitterName: "Omar Haddad",
      submitterEmail: "omar.haddad@uspto.gov",
      submitterRole: "trademark_examiner",
      submitterOffice: "uspto",
      reviewStatus: "in_review",
      useCaseTitle: "Trademark Conflict Search Advisory Assistant",
      useCaseDescription:
        "An advisory assistant that surfaces the most likely conflicting prior trademarks for an examining attorney, with the basis for each match. The attorney decides the refusal; the AI never issues it.",
      publicIndicator: "public",
      targetAudience: "other",
      impactedUsersCount: "gt_500",
      painPoints: "Conflict search is manual and varies by attorney; similar marks get missed, driving pendency and inconsistent refusals.",
      targetUserContext: "USPTO trademark examining attorneys and the supervisors who review their determinations.",
      targetUserSummary: "Trademark examining attorneys performing likelihood-of-confusion conflict searches.",
      coreProblem: "Manual, attorney-by-attorney conflict search misses similar marks and produces inconsistent refusals.",
      problemImpact: "Inconsistent search lengthens examination and produces uneven Section 2(d) outcomes.",
      affectedSystem: "other",
      problemType: ["productivity", "quality"],
      severity: "high",
      problemDefinition: "Examiners lack a consistent, advisory way to surface likely conflicting marks across phonetic, visual, and goods/services signals.",
      proposedSolution:
        "A retrieval/ranking assistant surfacing likely conflicting marks with the basis for each (phonetic, visual, goods/services relatedness). The attorney reviews and decides; the AI never issues a refusal. U.S.-hosted.",
      keyFunctionality: ["search", "ranking", "summarization"],
      solutionSummary: "Advisory, ranked conflict-mark surfacing with basis shown; attorney decides. U.S.-hosted.",
      userValue: "Cuts conflict-search time and surfaces marks an attorney might miss, with reasoning shown.",
      userTimeSavings: "5_10",
      otherUserImprovements: ["better_decisions", "more_consistent_work"],
      userValueSummary: "Faster, more consistent conflict search with the basis shown; attorney decides.",
      businessValue: "Reduces trademark pendency and improves consistency of Section 2(d) refusals.",
      costSavings: "gt_1m",
      strategicBenefit: ["reduce_pendency", "improve_quality"],
      businessValueSummary: "Lower conflict-search time and more consistent outcomes at scale.",
      usptoFocusArea: ["omb_governance", "high_impact_mgmt"],
      relevantOkrs: "Trademark pendency and quality; responsible-AI use with human oversight.",
      alignmentSummary: "Advances efficient delivery of reliable IP rights under a responsible-AI, attorney-in-the-loop design.",
      implementationComplexity: "medium",
      resourcesNeeded: ["ml_engineers", "examiner_sme", "infrastructure"],
      dependencies: "Trademark register and design-code data; examiner workbench integration; U.S.-hosted model.",
      involvesSensitiveData: "no",
      securityClassification: "internal",
      accessControlRequirements: ["employee_authentication", "audit_logging"],
      aiDecisionalImpact: "no",
      aiModelSourcing: "american_built",
      aiHumanReview: "yes",
      // Clearly REPORTABLE: not NSS/IC, not research-only, and a stage is set —
      // supports mission/service delivery per lib/ombReportability.ts.
      stageOfDevelopment: "pilot",
      nationalSecuritySystem: "no",
      researchOnly: "no",
      highImpact: "no",
      hasATO: "in_progress",
      systemSource: "contract",
      feasibilitySummary: "Medium complexity; advisory only, attorney decides, basis shown. American-built, U.S.-hosted; workbench integration is the main lift.",
      successMetrics: "Conflict-search time per application, surfaced-mark relevance, 2(d) consistency, pendency in pilot offices vs control.",
      keyMetrics: ["time_saved", "quality_improvement", "user_satisfaction"],
      timelineForResults: "6_12",
      metricsSummary: "Pilot measures search time, relevance, consistency, and pendency vs a control.",
      routeTo: ["governance"],
      reviewerNotes: "Strong, high-value examiner-assist with a clean responsible-AI posture. In review.",
      readinessScore: "ready",
      readinessSummary: "Comprehensive, measurable, well-aligned; advisory, attorney-in-the-loop, American-built. Ready for review.",
      executiveSummary:
        "Trademark conflict search is manual and varies by attorney, so similar marks get missed and refusals are inconsistent. This advisory assistant surfaces likely conflicting marks with the basis for each; the attorney decides, and the AI never issues a refusal. Expected: 30-40% less search time and more consistent outcomes. American-built, attorney-in-the-loop. Ready for review.",
    } as Partial<FormData>),
  },

  // 6) NOAA — public summarization. Needs info (action-needed loop).
  {
    id: "doc-noaa-alert-summaries",
    submittedAt: hoursAgo(52),
    formData: mk({
      submitterName: "Carlos Mendez",
      submitterEmail: "carlos.mendez@noaa.gov",
      submitterRole: "other",
      submitterOffice: "noaa",
      submitterSubOffice: "nws",
      reviewStatus: "needs_info",
      comments: [
        {
          id: "c-noaa-1",
          authorName: "Jordan Pierce",
          authorRole: "reviewer",
          body: "Promising and public-facing. Before scoring: what's the human-review step before anything publishes, and how do we guarantee it never alters the official alert's meaning?",
          createdAt: hoursAgo(20),
        },
      ],
      useCaseTitle: "Plain-Language Severe-Weather Alert Summaries",
      useCaseDescription:
        "Generates plain-language, accessible summaries of official severe-weather alerts for the public, with the official alert always shown alongside. A forecaster reviews before anything publishes.",
      publicIndicator: "public",
      targetAudience: "applicant",
      impactedUsersCount: "gt_500",
      painPoints: "Official alerts are technical; the public, including limited-English and low-vision users, can struggle to act quickly.",
      targetUserContext: "Members of the public receiving severe-weather alerts, especially limited-English and assistive-technology users.",
      targetUserSummary: "The public receiving severe-weather alerts; forecasters who must review any public-facing wording.",
      coreProblem: "Technical alert language slows public understanding and action, with the burden falling on vulnerable groups.",
      problemImpact: "Slower comprehension can delay protective action during severe weather.",
      affectedSystem: "cross_functional",
      problemType: ["user_experience"],
      severity: "high",
      problemDefinition: "The public lacks fast, plain-language, accessible understanding of official severe-weather alerts.",
      proposedSolution:
        "An assistant that drafts a plain-language summary of an official alert, always shown next to the official text, reviewed and approved by a forecaster before publishing. It never replaces or alters the official alert.",
      keyFunctionality: ["summarization", "translation"],
      solutionSummary: "Forecaster-approved plain-language summaries shown alongside the official alert. Never replaces the official text.",
      userValue: "The public understands and acts on alerts faster, in plain language and multiple languages.",
      userTimeSavings: "lt_1",
      otherUserImprovements: ["better_decisions", "less_frustration"],
      userValueSummary: "Faster public comprehension of alerts; official text always shown.",
      businessValue: "Improves public safety outcomes and accessibility of life-safety information.",
      costSavings: "lt_50k",
      strategicBenefit: ["employee_experience"],
      businessValueSummary: "Faster, more accessible public understanding of life-safety alerts.",
      usptoFocusArea: ["customer_experience", "omb_public_trust", "high_impact_mgmt"],
      relevantOkrs: "Public accessibility of alerts; responsible-AI use with mandatory human review.",
      alignmentSummary: "Public good and accessibility, with a human-in-the-loop, never-alter-the-official-text design.",
      implementationComplexity: "medium",
      resourcesNeeded: ["ml_engineers", "content_owner"],
      dependencies: "Official alert feed; forecaster review workflow; multilingual + 508 review.",
      involvesSensitiveData: "no",
      securityClassification: "internal",
      accessControlRequirements: ["audit_logging"],
      aiDecisionalImpact: "yes",
      aiModelSourcing: "american_built",
      aiHumanReview: "yes",
      // High-impact example (OMB M-25-21 additional risk-management reporting):
      // public-facing, life-safety, AI-decisional — risk fields populated below.
      stageOfDevelopment: "pilot",
      highImpactFactors: ["safety"],
      highImpact: "yes",
      hasATO: "in_progress",
      systemSource: "contract",
      aiImpactAssessment:
        "Intended purpose: faster public comprehension of severe-weather alerts. Expected benefit: quicker protective action, especially for limited-English and low-vision users. Potential risk: a flawed summary could misrepresent an official alert, so the official text is always shown alongside and a forecaster reviews before publish.",
      preDeploymentTesting: "yes",
      preDeploymentTestingNote: "Piloted against a sample of historical alerts with forecaster review before wider rollout.",
      ongoingMonitoringPlan: "yes",
      ongoingMonitoringNote: "Forecaster approval rate and comprehension metrics tracked each release; any drift triggers a re-review.",
      humanOversightAppeal: "yes",
      humanOversightAppealNote: "Forecaster reviews and can reject any summary before it publishes; the official alert is always shown alongside for the public to compare.",
      feasibilitySummary: "Public, life-safety context, so this is high-impact: mandatory forecaster review before publish, official text always shown, validated accuracy. American-built.",
      successMetrics: "Comprehension/time-to-action in testing, forecaster approval rate, accessibility conformance — vs current.",
      keyMetrics: ["user_satisfaction", "quality_improvement"],
      timelineForResults: "6_12",
      metricsSummary: "Measures comprehension, forecaster approval, and accessibility before scaling.",
      routeTo: ["governance"],
      reviewerNotes: "High-impact, life-safety. Needs the human-review gate and a guarantee it never alters official meaning.",
      readinessScore: "needs_work",
      readinessSummary: "Valuable, public-good case, but high-impact and life-safety: needs an explicit mandatory forecaster-review gate and a guarantee it never alters the official alert before scoring.",
      executiveSummary:
        "Official severe-weather alerts are technical, slowing public understanding and action. This assistant drafts a plain-language summary shown alongside the official alert, approved by a forecaster before publishing, and never replaces the official text. High-impact and life-safety: needs an explicit human-review gate and accuracy guarantees before it advances.",
    } as Partial<FormData>),
  },

  // 7) BIS — internal triage with decisional considerations. Submitted; needs work.
  {
    id: "doc-bis-license-triage",
    submittedAt: hoursAgo(70),
    formData: mk({
      submitterName: "Helen Park",
      submitterEmail: "helen.park@bis.doc.gov",
      submitterRole: "manager",
      submitterOffice: "bis",
      reviewStatus: "submitted",
      useCaseTitle: "Export License Application Triage Assistant",
      useCaseDescription:
        "Classifies and routes incoming export license applications and flags likely-incomplete ones for a licensing officer, who makes every determination. Advisory only; never approves or denies.",
      publicIndicator: "public",
      targetAudience: "other",
      impactedUsersCount: "50_500",
      painPoints: "Applications queue for manual triage and routing; incomplete ones surface late, adding cycle time.",
      targetUserContext: "BIS licensing officers and triage staff handling export license applications.",
      targetUserSummary: "BIS licensing officers and triage staff; the AI advises, the officer decides.",
      coreProblem: "Manual triage and routing of license applications is slow, and incompleteness is caught late.",
      problemImpact: "Slow triage and late-caught gaps add cycle time to license processing.",
      affectedSystem: "cross_functional",
      problemType: ["productivity"],
      severity: "medium",
      problemDefinition: "License applications lack fast, consistent triage/routing and early completeness checks.",
      proposedSolution:
        "A classifier that predicts category and routing and flags likely-incomplete applications for an officer, who makes every determination. Advisory only; never approves or denies; full audit logging.",
      keyFunctionality: ["classification", "routing"],
      solutionSummary: "Advisory triage/routing + completeness flags; officer decides. Never approves or denies. Logged.",
      userValue: "Officers spend less time on routing and catch gaps earlier, with the decision firmly theirs.",
      userTimeSavings: "1_5",
      otherUserImprovements: ["more_consistent_work"],
      userValueSummary: "Faster routing and earlier completeness checks; officer decides.",
      businessValue: "Reduces license-processing cycle time and rework, with no decisional AI.",
      costSavings: "50k_250k",
      strategicBenefit: ["operational_efficiency"],
      businessValueSummary: "Lower cycle time and rework; officer-in-the-loop throughout.",
      usptoFocusArea: ["omb_governance", "high_impact_mgmt", "american_ai"],
      relevantOkrs: "License-processing cycle time; responsible-AI use with mandatory human review.",
      alignmentSummary: "Operational efficiency under a strict advisory-only, officer-decides design given the sensitivity of export control.",
      implementationComplexity: "medium",
      resourcesNeeded: ["ml_engineers", "examiner_sme"],
      dependencies: "Historical application data; case-management integration; a measured baseline (not yet collected).",
      involvesSensitiveData: "yes",
      securityClassification: "controlled",
      accessControlRequirements: ["pii_protection", "employee_authentication", "audit_logging"],
      aiDecisionalImpact: "no",
      aiModelSourcing: "american_built",
      aiHumanReview: "yes",
      // Clearly EXCLUDED: this signal set feeds export-control enforcement
      // determinations tied to national security, so it's flagged as a
      // National Security System / IC use and excluded from the OMB inventory
      // per lib/ombReportability.ts (independent of its workflow status).
      stageOfDevelopment: "pre_deployment",
      nationalSecuritySystem: "yes",
      researchOnly: "no",
      highImpact: "no",
      hasATO: "no",
      systemSource: "in_house",
      feasibilitySummary: "Sensitive export-control context: advisory only, officer decides, controlled data handling, full logging. Needs a measured baseline.",
      successMetrics: "Triage time, misroute rate, share of incomplete apps caught early — vs a baseline.",
      keyMetrics: ["resolution_time", "error_rate", "productivity"],
      timelineForResults: "6_12",
      metricsSummary: "Tracks triage time and misroutes against a baseline (to be collected).",
      routeTo: ["governance"],
      reviewerNotes: "Sensitive domain; confirm advisory-only design and collect a baseline before scoring.",
      readinessScore: "needs_work",
      readinessSummary: "Useful operational case in a sensitive domain. Needs a measured baseline and explicit confirmation it never approves or denies a license.",
      executiveSummary:
        "BIS export license applications queue for manual triage, and incomplete ones surface late. This advisory assistant predicts routing and flags incompleteness for a licensing officer, who makes every determination — it never approves or denies. Sensitive domain, controlled data, officer-in-the-loop. Needs a measured baseline before scoring.",
    } as Partial<FormData>),
  },

  // 8) MBDA — auto-scoring loan/grant eligibility. Rejected: foreign model
  // sourcing and no mandatory human review on a decision affecting applicants.
  {
    id: "doc-mbda-loan-eligibility-bot",
    submittedAt: hoursAgo(90),
    formData: mk({
      submitterName: "Victor Ibarra",
      submitterEmail: "victor.ibarra@mbda.gov",
      submitterRole: "product_owner",
      submitterOffice: "mbda",
      reviewStatus: "rejected",
      comments: [
        {
          id: "c-mbda-1",
          authorName: "Jordan Pierce",
          authorRole: "reviewer",
          body: "Rejected as scoped: a foreign-hosted model auto-deciding loan/grant eligibility with no mandatory human review doesn't meet the executive order on model sourcing or our decisional-AI human-review requirement. Resubmit with an American-built model and an officer-in-the-loop approval step before this can be reconsidered.",
          createdAt: hoursAgo(60),
        },
      ],
      useCaseTitle: "Automated Loan & Grant Eligibility Matcher",
      useCaseDescription:
        "An AI system that automatically scores minority business enterprise applicants against federal loan and grant program criteria and issues an eligibility determination without officer review.",
      publicIndicator: "public",
      targetAudience: "applicant",
      impactedUsersCount: "50_500",
      painPoints: "Eligibility screening is manual and slow, and application volume is outpacing reviewer capacity.",
      targetUserContext: "Minority business enterprise applicants to MBDA-affiliated loan and grant programs.",
      targetUserSummary: "MBE applicants awaiting an eligibility determination for federal loan/grant programs.",
      coreProblem: "Manual eligibility screening is slow and inconsistent as application volume grows.",
      problemImpact: "Applicants wait longer for a determination, and screening quality varies by reviewer.",
      affectedSystem: "other",
      problemType: ["productivity", "quality"],
      severity: "high",
      problemDefinition: "Eligibility screening lacks a fast, consistent, and compliant automated path.",
      proposedSolution:
        "A scoring model that ingests applicant financials and program criteria and issues a determination directly to the applicant, using a third-party foreign-hosted model to minimize cost.",
      keyFunctionality: ["classification", "ranking"],
      solutionSummary: "Automated eligibility scoring and determination issuance using a foreign-hosted model.",
      userValue: "Applicants would get a faster answer, if the determination were trustworthy.",
      userTimeSavings: "1_5",
      otherUserImprovements: ["less_frustration"],
      userValueSummary: "Faster (but currently unvetted) eligibility answers for MBE applicants.",
      businessValue: "Would reduce screening backlog, but not at the cost of a non-compliant decisional system.",
      costSavings: "50k_250k",
      strategicBenefit: ["operational_efficiency"],
      businessValueSummary: "Backlog reduction only justifies the risk once sourcing and human review are fixed.",
      usptoFocusArea: ["american_ai", "high_impact_mgmt"],
      relevantOkrs: "Loan/grant processing time; American-built model sourcing (EO 14179); mandatory human review.",
      alignmentSummary: "Operational goal is sound, but the current design conflicts with federal AI sourcing and human-review requirements.",
      implementationComplexity: "medium",
      resourcesNeeded: ["ml_engineers", "infrastructure"],
      dependencies: "Applicant financial data access; a compliant (American-built) model; an officer-review workflow that does not yet exist.",
      involvesSensitiveData: "yes",
      securityClassification: "controlled",
      accessControlRequirements: ["pii_protection", "audit_logging"],
      aiDecisionalImpact: "yes",
      aiModelSourcing: "foreign",
      aiHumanReview: "no",
      stageOfDevelopment: "pre_deployment",
      highImpact: "no",
      hasATO: "no",
      systemSource: "vendor",
      feasibilitySummary: "Rejected as designed: foreign-hosted model plus a fully-automated decision affecting applicants, with no human review — non-compliant on two mandated AI risk questions.",
      successMetrics: "Screening time and backlog size — not yet measurable given the compliance blockers.",
      keyMetrics: ["resolution_time", "productivity"],
      timelineForResults: "3_6",
      metricsSummary: "Not applicable until the sourcing and human-review issues are resolved.",
      routeTo: ["governance"],
      reviewerNotes: "Rejected: foreign model sourcing and no human review on a decision directly affecting applicants. Resubmit with American-built sourcing and an officer-approval step.",
      readinessScore: "early_stage",
      readinessSummary: "Not fundable as scoped — non-compliant model sourcing and no human review on an applicant-facing decision. Rework required before resubmission.",
      executiveSummary:
        "MBDA's manual loan/grant eligibility screening is slow, but this proposal would auto-issue determinations to applicants using a foreign-hosted model with no human review — non-compliant with EO 14179 and DoC's decisional-AI human-review mandate. Rejected as scoped; resubmit with American-built sourcing and an officer-in-the-loop approval step.",
    } as Partial<FormData>),
  },

  // 9) CENSUS (Decennial office) — submitter-owned draft, stopped partway
  // through the wizard. Deliberately sparse past the early steps so the
  // submitter's own "My ideas" view has something real to resume/track.
  {
    id: "doc-census-decennial-draft",
    submittedAt: hoursAgo(2),
    formData: mk({
      submitterName: "Leah Ochoa",
      submitterEmail: "leah.ochoa@census.gov",
      submitterRole: "product_owner",
      submitterOffice: "census",
      submitterSubOffice: "decennial",
      reviewStatus: "draft",
      useCaseTitle: "Decennial Field Data Quality Triage",
      useCaseDescription:
        "An assistant to help field data quality staff triage flagged decennial enumeration records faster. Still drafting the proposed solution and value case.",
      targetAudience: "other",
      impactedUsersCount: "50_500",
      painPoints: "Flagged records pile up faster than staff can review them during peak collection.",
      targetUserContext: "Decennial field data quality staff reviewing flagged enumeration records.",
      targetUserSummary: "Decennial field data quality reviewers.",
      coreProblem: "Flagged enumeration records queue faster than staff can triage them during peak collection.",
      problemImpact: "Backlog grows during the peak collection window, delaying downstream processing.",
      affectedSystem: "other",
      problemType: ["productivity"],
      severity: "medium",
      problemDefinition: "Field data quality staff lack a fast way to triage the flagged-record backlog during peak collection.",
    } as Partial<FormData>),
  },
]
